In [1562]:
# Import Libraries to read and plot datasets
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale
from collections import Counter
import regex

In [1563]:
crash_data = pd.read_csv("hq1d-p-app52dopendataexport2025crashes.csv")

C:\Users\Evan\AppData\Local\Temp\ipykernel_80748\1470525132.py:1: DtypeWarning: Columns (0: 	NCIC Code, 1: 	City Is Active, 2: 	City Is Incorporated, 3: 	IsHighwayRelated, 4: 	IsTowAway, 5:  Road Condition 2, 6: MilepostUnitOfMeasure, 7: 	ReportingDistrictCode, 8: 	SketchDesc, 9: IsCountyRoad, 10: IsFreeway, 11: 	IsAdditonalObjectStruck, 12: NotificationDate, 13: 	NotificationTimeDescription, 14: 	HasDigitalMediaFiles, 15: 	EvidenceNumber, 16: 	IsLocationReferToNarrative, 17: 	IsAOIOneSameAsLocation) have mixed types. Specify dtype option on import or set low_memory=False.
  crash_data = pd.read_csv("hq1d-p-app52dopendataexport2025crashes.csv")

In [1564]:
len(crash_data)

393510

In [1565]:
crash_data.head()

,Collision Id,\tReport Number,\tReport Version,\tIs Preliminary,\tNCIC Code,Crash Date Time,\tCrash Time Description,\tBeat,City Id,\tCity Code,...,IsCountyRoad,IsFreeway,CHP555Version,\tIsAdditonalObjectStruck,NotificationDate,\tNotificationTimeDescription,\tHasDigitalMediaFiles,\tEvidenceNumber,\tIsLocationReferToNarrative,\tIsAOIOneSameAsLocation
0,4550265,9685-2025-00096,1,False,9685,1/18/2025 3:20:00 PM,1520,039,994.0,3300.0,...,False,False,4,NaN,1/18/2025 3:25:00 PM,1525,False,NaN,NaN,True
1,4550264,250110005,1,False,4116,1/10/2025 8:28:00 AM,828,A,1310.0,4116.0,...,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4550263,9580-2025-00214,1,False,9580,1/23/2025 8:45:00 AM,845,171,535.0,1942.0,...,False,True,4,NaN,1/23/2025 8:47:00 AM,0847,False,NaN,NaN,True
3,4550262,9765-2025-00066,1,False,9765,1/15/2025 12:30:00 PM,1230,041,1701.0,5606.0,...,False,True,4,NaN,1/15/2025 12:35:00 PM,1235,True,EMBEDDED,NaN,True
4,4550261,9426-2025-00035,1,False,9426,1/20/2025 12:30:00 PM,1230,460,397.0,1500.0,...,True,False,4,NaN,1/20/2025 12:32:00 PM,1232,False,NaN,NaN,True

In [1566]:
crash_data.columns = crash_data.columns.str.strip()

In [1567]:
crash_parties_data = pd.read_csv("a2676918-a825-4b77-8e5c-6eadb38d6b1a.csv")

In [1568]:
len(crash_parties_data)

767052

In [1569]:
crash_parties_data

,_id,PartyId,CollisionId,PartyNumber,PartyType,IsAtFault,IsOnDutyEmergencyVehicle,IsHitAndRun,AirbagCode,AirbagDescription,...,Vehicle2TypeDesc,Vehicle2Year,Vehicle2Make,Vehicle2Model,Vehicle2Color,V2IsVehicleTowed,Lane,ThruLanes,TotalLanes,IsDREConducted
0,1,13900346,4541902,1,Driver,True,False,True,B,UNKNOWN,...,NaN,NaN,NaN,NaN,NaN,NaN,N/B,1.0,1.0,False
1,2,13900345,4541901,2,Driver,NaN,False,False,M,AIR BAG NOT DEPLOYED,...,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,5.0,False
2,3,13900344,4541901,1,Driver,True,False,False,L,AIR BAG DEPLOYED,...,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,5.0,False
3,4,13900343,4541900,2,Driver,NaN,False,False,M,AIR BAG NOT DEPLOYED,...,NaN,NaN,NaN,NaN,NaN,NaN,E/B,1.0,1.0,False
4,5,13900342,4541900,1,Driver,NaN,False,False,M,AIR BAG NOT DEPLOYED,...,NaN,NaN,NaN,NaN,NaN,NaN,N/B,1.0,1.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
767047,767048,14979609,5105674,1,Driver,True,False,NaN,M,AIR BAG NOT DEPLOYED,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1.0,1.0,NaN
767048,767049,14979608,5105673,1,Driver,True,False,NaN,M,AIR BAG NOT DEPLOYED,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1.0,1.0,NaN
767049,767050,14979607,5105672,2,Driver,NaN,False,NaN,M,AIR BAG NOT DEPLOYED,...,NaN,NaN,NaN,NaN,NaN,NaN,1,3.0,3.0,NaN
767050,767051,14979606,5105672,1,Driver,True,False,NaN,M,AIR BAG NOT DEPLOYED,...,NaN,NaN,NaN,NaN,NaN,NaN,2,3.0,3.0,NaN
767051,767052,14979605,5105671,2,Driver,NaN,False,NaN,M,AIR BAG NOT DEPLOYED,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1570]:
crash_data = crash_data.drop(['Report Number','Report Version','Is Preliminary','NCIC Code','City Is Active',
       'City Is Incorporated', 'Collision Type Code','HasPhotographs', 'IsAttachmentsMailed', 'IsDeleted','JudicialDistrict', 'MotorVehicleInvolvedWithCode', 'MilepostDirection', 'MilepostDistance', 'MilepostMarker',
       'MilepostUnitOfMeasure', 'PreparedDate','ReportingDistrict',
       'ReportingDistrictCode', 'ReviewedDate', 'RoadwaySurfaceCode',
       'SecondaryDirection', 'SecondaryDistance', 'SecondaryRoad',
       'SecondaryUnitOfMeasure', 'SketchDesc', 'TrafficControlDeviceCode',
       'CreatedDate', 'ModifiedDate','CHP555Version', 'NotificationTimeDescription', 'HasDigitalMediaFiles', 'EvidenceNumber',
       'IsLocationReferToNarrative', 'DispatchNotified','Crash Time Description', 'Beat', 'City Id', 'City Code','Weather 2','Road Condition 2','Special Condition','Collision Type Other Desc','NotificationDate', 'IsAOIOneSameAsLocation',
        'IsCountyRoad'], axis = 1)

In [1571]:
if crash_data.duplicated().sum() > 0:
    dropped_duplicates_crash_data = crash_data.drop_duplicates() #drop any duplicate rows in the dataframe

In [1572]:
crash_data.columns

Index(['Collision Id', 'Crash Date Time', 'City Name', 'County Code',
       'Collision Type Description', 'Day Of Week', 'HitRun',
       'IsHighwayRelated', 'IsTowAway', 'MotorVehicleInvolvedWithDesc',
       'MotorVehicleInvolvedWithOtherDesc', 'NumberInjured', 'NumberKilled',
       'Weather 1', 'Road Condition 1', 'LightingCode', 'LightingDescription',
       'Latitude', 'Longitude', 'PedestrianActionCode', 'PedestrianActionDesc',
       'Primary Collision Factor Code', 'Primary Collision Factor Violation',
       'PrimaryCollisionFactorIsCited', 'PrimaryCollisionPartyNumber',
       'PrimaryRoad', 'IsFreeway', 'IsAdditonalObjectStruck'],
      dtype='str')

In [1573]:
crash_data_roads = crash_data[['Collision Id','PrimaryRoad','IsFreeway','IsHighwayRelated']]

In [1574]:
crash_data_roads.head()

   Collision Id                  PrimaryRoad IsFreeway IsHighwayRelated
0       4550265                    SR-79 N/B     False             True
1       4550264             N EL CAMINO REAL       NaN            False
2       4550263  SR-170 S/B FROM SHERMAN WAY      True             True
3       4550262                   SR-126 E/B      True             True
4       4550261                    SR-46 W/B     False            False

In [1575]:
#How many values within the IsHighwayRelated Column is NaN 
crash_data_roads['IsHighwayRelated'].isna().sum()

np.int64(1)

In [1576]:
#How many values within isFreeway Column is NaN
crash_data_roads['IsFreeway'].isna().sum()

np.int64(179605)

In [1577]:
#backfill IsFreeway column with IsHighwayRelated column values and fill in any remaining NaN values with False
crash_data_roads['IsFreeway'] = crash_data_roads['IsFreeway'].fillna(crash_data_roads['IsHighwayRelated']).fillna(False)


#crash_data_roads = crash_data_roads.fillna(False, axis = 1) #fill in NA fields with False since it should only be True or False

In [1578]:
#confirm above worked and there are no more NaN values in the IsFreeway column
crash_data_roads['IsFreeway'].isna().sum()

np.int64(0)

In [1579]:
crash_data_roads['IsHighwayRelated'].isna().sum()

np.int64(1)

In [1580]:
#Add this since I did not realize that there was one NaN value in the IsHighwayRelated column. Fill it with False since it should only be True or False
crash_data_roads['IsHighwayRelated'] = crash_data_roads['IsHighwayRelated'].fillna(False)

In [1581]:
crash_data_roads.count() # confirming that the fields that should be here

Collision Id        393510
PrimaryRoad         393510
IsFreeway           393510
IsHighwayRelated    393510
dtype: int64

In [1582]:
freeway_crashes = crash_data_roads[crash_data_roads['IsFreeway'] == True]

In [1583]:
local_crashes = crash_data_roads[crash_data_roads['IsFreeway'] == False]

In [1584]:
local_crashes

        Collision Id             PrimaryRoad IsFreeway IsHighwayRelated
0            4550265               SR-79 N/B     False             True
1            4550264        N EL CAMINO REAL     False            False
4            4550261               SR-46 W/B     False            False
7            4550258  SR-74 (ORTEGA HWY) W/B     False             True
10           4550253                 83RD ST     False            False
...              ...                     ...       ...              ...
393504       5105492             PROSPECT ST     False            False
393505       5105490                 MAIN ST     False            False
393506       5105489             LA VETA AVE     False            False
393507       5105488               CANNON ST     False            False
393509       5105486               TUSTIN ST     False            False

[250919 rows x 4 columns]

In [1585]:
assert(len(local_crashes) + len(freeway_crashes)) == 393510 # assert that the divide between local and highway crashes add up to the original amount

In [1586]:
local_crashes.to_csv("local_crashes.csv")

In [1587]:
freeway_crashes.to_csv("freeway_crashes.csv")

In [1588]:
crash_data_roads.rename(columns = {'Collision Id':'CollisionId'}, inplace = True)

In [1589]:
crash_data_roads.to_csv("crash_data_roads.csv",index=False)

In [1590]:
crash_data[crash_data['IsAdditonalObjectStruck'].isna() ==True]['IsAdditonalObjectStruck']

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
393505    NaN
393506    NaN
393507    NaN
393508    NaN
393509    NaN
Name: IsAdditonalObjectStruck, Length: 370507, dtype: object

In [1591]:
crash_data[crash_data['IsAdditonalObjectStruck'] ==True]['IsAdditonalObjectStruck']

19        True
46        True
56        True
58        True
62        True
          ...
392787    True
392798    True
392806    True
392811    True
392815    True
Name: IsAdditonalObjectStruck, Length: 17631, dtype: object

In [1592]:
crash_data[crash_data['IsAdditonalObjectStruck'] == False]['IsAdditonalObjectStruck']

49        False
122       False
137       False
249       False
258       False
          ...
387969    False
388561    False
392354    False
392381    False
392813    False
Name: IsAdditonalObjectStruck, Length: 5372, dtype: object

Given that the majority of the values in IsAdditonalObjectStruck is NaN / Null and this was supposed to be only True or False and no additional information on what additional object means, it will be best to drop this column

In [1593]:
crash_data = crash_data.drop(['IsAdditonalObjectStruck'], axis = 1)

In [1594]:
crash_data.columns

Index(['Collision Id', 'Crash Date Time', 'City Name', 'County Code',
       'Collision Type Description', 'Day Of Week', 'HitRun',
       'IsHighwayRelated', 'IsTowAway', 'MotorVehicleInvolvedWithDesc',
       'MotorVehicleInvolvedWithOtherDesc', 'NumberInjured', 'NumberKilled',
       'Weather 1', 'Road Condition 1', 'LightingCode', 'LightingDescription',
       'Latitude', 'Longitude', 'PedestrianActionCode', 'PedestrianActionDesc',
       'Primary Collision Factor Code', 'Primary Collision Factor Violation',
       'PrimaryCollisionFactorIsCited', 'PrimaryCollisionPartyNumber',
       'PrimaryRoad', 'IsFreeway'],
      dtype='str')

In [1595]:
#Check if TowAway column has any NaN values. 
crash_data['IsTowAway'].isna().sum()

np.int64(99)

In [1596]:
crash_data.loc[crash_data['IsTowAway'].isna(), 'IsTowAway'] = False

In [1597]:
assert(crash_data['IsTowAway'].isna().sum() == 0) #confirm that there are no more NaN values in the IsTowAway column

In [1598]:
#Assert the above worked
assert('IsAdditonalObjectStruck' not in crash_data.columns)

In [1599]:
crash_injuries = crash_data[['Collision Id','IsTowAway','MotorVehicleInvolvedWithDesc','MotorVehicleInvolvedWithOtherDesc','NumberInjured','NumberKilled',
'Primary Collision Factor Code', 'Primary Collision Factor Violation', 'PrimaryCollisionFactorIsCited', 'PrimaryCollisionPartyNumber']]

In [1600]:
crash_injuries.head()

,Collision Id,IsTowAway,MotorVehicleInvolvedWithDesc,MotorVehicleInvolvedWithOtherDesc,NumberInjured,NumberKilled,Primary Collision Factor Code,Primary Collision Factor Violation,PrimaryCollisionFactorIsCited,PrimaryCollisionPartyNumber
0,4550265,True,NON-COLLISION,NaN,1.0,0.0,A,VC 22107,False,1.0
1,4550264,False,OTHER MOTOR VEHICLE,NaN,1.0,0.0,A,22350 VC,False,1.0
2,4550263,False,OTHER MOTOR VEHICLE,NaN,0.0,0.0,A,VC 22107,False,1.0
3,4550262,False,OTHER OBJECT,METAL OBJECT,0.0,0.0,A,VC 22350,False,1.0
4,4550261,True,OTHER MOTOR VEHICLE,NaN,3.0,0.0,A,VC 22450(a),False,1.0

In [1601]:
crash_injuries

,Collision Id,IsTowAway,MotorVehicleInvolvedWithDesc,MotorVehicleInvolvedWithOtherDesc,NumberInjured,NumberKilled,Primary Collision Factor Code,Primary Collision Factor Violation,PrimaryCollisionFactorIsCited,PrimaryCollisionPartyNumber
0,4550265,True,NON-COLLISION,NaN,1.0,0.0,A,VC 22107,False,1.0
1,4550264,False,OTHER MOTOR VEHICLE,NaN,1.0,0.0,A,22350 VC,False,1.0
2,4550263,False,OTHER MOTOR VEHICLE,NaN,0.0,0.0,A,VC 22107,False,1.0
3,4550262,False,OTHER OBJECT,METAL OBJECT,0.0,0.0,A,VC 22350,False,1.0
4,4550261,True,OTHER MOTOR VEHICLE,NaN,3.0,0.0,A,VC 22450(a),False,1.0
...,...,...,...,...,...,...,...,...,...,...
393505,5105490,True,OTHER MOTOR VEHICLE,NaN,0.0,0.0,A,21801(a),False,1.0
393506,5105489,True,OTHER MOTOR VEHICLE,NaN,2.0,0.0,A,21453(a),False,1.0
393507,5105488,False,OTHER MOTOR VEHICLE,NaN,1.0,0.0,A,21801(a),False,1.0
393508,5105487,True,OTHER MOTOR VEHICLE,NaN,1.0,0.0,A,22350,False,1.0
393509,5105486,True,FIXED OBJECT,CURB,0.0,0.0,A,22350,False,1.0

In [1602]:
crash_injuries['Primary Collision Factor Code'].value_counts()

Primary Collision Factor Code
A    361426
B     12369
C     10314
D      9137
Name: count, dtype: int64

It seems that for almost 92% of all reported accidents in CA in 2025, is the cause of some vehicle code being broken and not B - Other Improper Driving C - Other Than Driver D - Unknown E - Fell Asleep. Thus We should only be focusing on A

In [1603]:
primary_collision_factor_violation_values_A = crash_injuries[crash_injuries['Primary Collision Factor Code'] == 'A']

In [1604]:
primary_collision_factor_violation_values_A

,Collision Id,IsTowAway,MotorVehicleInvolvedWithDesc,MotorVehicleInvolvedWithOtherDesc,NumberInjured,NumberKilled,Primary Collision Factor Code,Primary Collision Factor Violation,PrimaryCollisionFactorIsCited,PrimaryCollisionPartyNumber
0,4550265,True,NON-COLLISION,NaN,1.0,0.0,A,VC 22107,False,1.0
1,4550264,False,OTHER MOTOR VEHICLE,NaN,1.0,0.0,A,22350 VC,False,1.0
2,4550263,False,OTHER MOTOR VEHICLE,NaN,0.0,0.0,A,VC 22107,False,1.0
3,4550262,False,OTHER OBJECT,METAL OBJECT,0.0,0.0,A,VC 22350,False,1.0
4,4550261,True,OTHER MOTOR VEHICLE,NaN,3.0,0.0,A,VC 22450(a),False,1.0
...,...,...,...,...,...,...,...,...,...,...
393505,5105490,True,OTHER MOTOR VEHICLE,NaN,0.0,0.0,A,21801(a),False,1.0
393506,5105489,True,OTHER MOTOR VEHICLE,NaN,2.0,0.0,A,21453(a),False,1.0
393507,5105488,False,OTHER MOTOR VEHICLE,NaN,1.0,0.0,A,21801(a),False,1.0
393508,5105487,True,OTHER MOTOR VEHICLE,NaN,1.0,0.0,A,22350,False,1.0
393509,5105486,True,FIXED OBJECT,CURB,0.0,0.0,A,22350,False,1.0

In [1605]:
primary_collision_factor_violation_values_A['Primary Collision Factor Violation'].value_counts()

Primary Collision Factor Violation
VC 22350                             55273
VC 22107                             37072
22350                                33788
22107                                31071
VC 21658(A)                          13432
                                     ...
21806(c)                                 1
23152(a/b)                               1
22100(a2)                                1
VC 21651(B) DRV WRONG HWY INJ/DTH        1
29003(a)                                 1
Name: count, Length: 2554, dtype: int64

In [1606]:
parsed_primary_collision_factor_violation_values_A = primary_collision_factor_violation_values_A['Primary Collision Factor Violation'].copy()

In [1607]:
parsed_primary_collision_factor_violation_values_A = primary_collision_factor_violation_values_A['Primary Collision Factor Violation'].astype(str)

In [1608]:
parsed_primary_collision_factor_violation_values_A

0            VC 22107
1            22350 VC
2            VC 22107
3            VC 22350
4         VC 22450(a)
             ...
393505       21801(a)
393506       21453(a)
393507       21801(a)
393508          22350
393509          22350
Name: Primary Collision Factor Violation, Length: 361426, dtype: str

In [1609]:
parsed_primary_collision_factor_violation_values_A = parsed_primary_collision_factor_violation_values_A.str.extract(r'(\d+)') # Series.str.extract(regex'(all decimals repeated)')

In [1610]:
parsed_primary_collision_factor_violation_values_A

            0
0       22107
1       22350
2       22107
3       22350
4       22450
...       ...
393505  21801
393506  21453
393507  21801
393508  22350
393509  22350

[361426 rows x 1 columns]

In [1611]:
parsed_primary_collision_factor_violation_values_A = parsed_primary_collision_factor_violation_values_A.rename({0: 'Violation Code Number'}, axis = 'columns')

In [1612]:
parsed_primary_collision_factor_violation_values_A

       Violation Code Number
0                      22107
1                      22350
2                      22107
3                      22350
4                      22450
...                      ...
393505                 21801
393506                 21453
393507                 21801
393508                 22350
393509                 22350

[361426 rows x 1 columns]

parsed_primary_collision_factor_violation_values_A has all the traffic code violations filtered out. Now we need to find what is the distribution of this.

In [1613]:
parsed_primary_collision_factor_violation_values_A.value_counts().head(5)

Violation Code Number
22350                    111508
22107                     82769
23152                     32700
21658                     29842
21453                     17256
Name: count, dtype: int64

Looking at the top 5 traffic violations involved in accidents, it seems to show that these 5 violations constitute over 75 percent of all accidents where some ticketable or worse offense occured.

These are what those traffic violations are: 

22350: Speeding

22107: Unsafe Lane Change

23152: DUI

21658: Not staying in Lane

21453: Red Light Violation

In [1614]:
type(primary_collision_factor_violation_values_A)

pandas.DataFrame

In [1615]:
primary_collision_factor_violation_values_A.insert(10, 'parsed_values', parsed_primary_collision_factor_violation_values_A) #Add the 10th column

In [1616]:
primary_collision_factor_violation_values_A.drop('Primary Collision Factor Violation', axis = 1 )

,Collision Id,IsTowAway,MotorVehicleInvolvedWithDesc,MotorVehicleInvolvedWithOtherDesc,NumberInjured,NumberKilled,Primary Collision Factor Code,PrimaryCollisionFactorIsCited,PrimaryCollisionPartyNumber,parsed_values
0,4550265,True,NON-COLLISION,NaN,1.0,0.0,A,False,1.0,22107
1,4550264,False,OTHER MOTOR VEHICLE,NaN,1.0,0.0,A,False,1.0,22350
2,4550263,False,OTHER MOTOR VEHICLE,NaN,0.0,0.0,A,False,1.0,22107
3,4550262,False,OTHER OBJECT,METAL OBJECT,0.0,0.0,A,False,1.0,22350
4,4550261,True,OTHER MOTOR VEHICLE,NaN,3.0,0.0,A,False,1.0,22450
...,...,...,...,...,...,...,...,...,...,...
393505,5105490,True,OTHER MOTOR VEHICLE,NaN,0.0,0.0,A,False,1.0,21801
393506,5105489,True,OTHER MOTOR VEHICLE,NaN,2.0,0.0,A,False,1.0,21453
393507,5105488,False,OTHER MOTOR VEHICLE,NaN,1.0,0.0,A,False,1.0,21801
393508,5105487,True,OTHER MOTOR VEHICLE,NaN,1.0,0.0,A,False,1.0,22350
393509,5105486,True,FIXED OBJECT,CURB,0.0,0.0,A,False,1.0,22350

In [1617]:
primary_collision_factor_violation_values_A['NumberKilled'].value_counts()

NumberKilled
 0.0    341278
 1.0      2144
 2.0       147
 3.0        18
 4.0         7
-1.0         1
 5.0         1
Name: count, dtype: int64

In [1618]:
type(primary_collision_factor_violation_values_A['NumberKilled'][0])

numpy.float64

In [1619]:
primary_collision_factor_violation_values_A.loc[primary_collision_factor_violation_values_A['NumberKilled'] == -1, 'NumberKilled'] = 0

In [1620]:
#Check if there are any NaN values in the NumberKilled column
primary_collision_factor_violation_values_A['NumberKilled'].isna().sum()

np.int64(17830)

In [1621]:
#Set them to 0 since it should only be 0 or greater
primary_collision_factor_violation_values_A.loc[primary_collision_factor_violation_values_A['NumberKilled'].isna(), 'NumberKilled'] = 0

In [1622]:
assert len(primary_collision_factor_violation_values_A['NumberKilled'].value_counts()) == primary_collision_factor_violation_values_A['NumberKilled'].nunique()  #confirm that all values are valid and there are no null values

In [1623]:
primary_collision_factor_violation_values_A.loc[primary_collision_factor_violation_values_A['NumberInjured'] == -1, 'NumberInjured'] = 0

In [1624]:
primary_collision_factor_violation_values_A.loc[primary_collision_factor_violation_values_A['NumberInjured'] < 0, 'NumberInjured'] = 0

In [1625]:
primary_collision_factor_violation_values_A.loc[primary_collision_factor_violation_values_A['NumberInjured'].isna(), 'NumberInjured'] = 0

In [1626]:
#Check if everything above worked as intended
primary_collision_factor_violation_values_A['NumberKilled'].isna().sum()

np.int64(0)

In [1627]:
#Check if the column of number killed has any negative values. It should not since it should only be 0 or greater
primary_collision_factor_violation_values_A[primary_collision_factor_violation_values_A['NumberKilled'] < 0] ['NumberKilled'].sum()

np.float64(0.0)

In [1628]:
primary_collision_factor_violation_values_A['NumberInjured'].value_counts()

NumberInjured
0.0     207831
1.0     111044
2.0      29943
3.0       8511
4.0       2679
5.0        914
6.0        310
7.0        105
8.0         49
9.0         20
10.0        10
12.0         4
11.0         4
13.0         1
20.0         1
Name: count, dtype: int64

In [1629]:
#Check if there are any NaN values in the NumberInjured column
primary_collision_factor_violation_values_A['NumberInjured'].isna().sum()

np.int64(0)

In [1630]:
#Check if the column of number injured has any negative values. It should not since it should only be 0 or greater
primary_collision_factor_violation_values_A[primary_collision_factor_violation_values_A['NumberInjured'] < 0] ['NumberInjured']

Series([], Name: NumberInjured, dtype: float64)

In [1631]:
#confirm that all values are valid and there are no null values
assert (primary_collision_factor_violation_values_A['NumberInjured'].nunique()) == len(primary_collision_factor_violation_values_A['NumberInjured'].value_counts()) 
assert (primary_collision_factor_violation_values_A['NumberInjured'].isna().sum() == 0)

In [1632]:
#Check if there are any NaN values in the MotorVehicleInvolvedWithDesc column
primary_collision_factor_violation_values_A[(primary_collision_factor_violation_values_A['MotorVehicleInvolvedWithDesc'] == '') | primary_collision_factor_violation_values_A['MotorVehicleInvolvedWithDesc'].isna()]['MotorVehicleInvolvedWithDesc']

1510      NaN
2187      NaN
2268      NaN
3141      NaN
10248     NaN
         ...
392309    NaN
392528    NaN
392575    NaN
392699    NaN
392766    NaN
Name: MotorVehicleInvolvedWithDesc, Length: 924, dtype: str

In [1633]:
#Fill in any blank values in the MotorVehicleInvolvedWithDesc column with N/A
primary_collision_factor_violation_values_A['MotorVehicleInvolvedWithDesc'] = primary_collision_factor_violation_values_A['MotorVehicleInvolvedWithDesc'].fillna('NOT-APPLICABLE')

In [1634]:
#Checking again if the above worked and assert that the filtered dataframe is empty, meaning there are no more NaN values in the MotorVehicleInvolvedWithDesc column
assert(primary_collision_factor_violation_values_A[(primary_collision_factor_violation_values_A['MotorVehicleInvolvedWithDesc'] == '') | primary_collision_factor_violation_values_A['MotorVehicleInvolvedWithDesc'].isna()]['MotorVehicleInvolvedWithDesc'].empty)

In [1635]:
primary_collision_factor_violation_values_A['MotorVehicleInvolvedWithDesc'].value_counts()

MotorVehicleInvolvedWithDesc
OTHER MOTOR VEHICLE               235689
FIXED OBJECT                       59173
PARKED MOTOR VEHICLE               28377
PEDESTRIAN                         10565
BICYCLE                             9185
NON-COLLISION                       7081
OTHER OBJECT                        6620
MOTOR VEHICLE ON OTHER ROADWAY      3533
NOT-APPLICABLE                       924
ANIMAL                               164
TRAIN                                115
Name: count, dtype: int64

In [1636]:
primary_collision_factor_violation_values_A['MotorVehicleInvolvedWithDesc']

0               NON-COLLISION
1         OTHER MOTOR VEHICLE
2         OTHER MOTOR VEHICLE
3                OTHER OBJECT
4         OTHER MOTOR VEHICLE
                 ...
393505    OTHER MOTOR VEHICLE
393506    OTHER MOTOR VEHICLE
393507    OTHER MOTOR VEHICLE
393508    OTHER MOTOR VEHICLE
393509           FIXED OBJECT
Name: MotorVehicleInvolvedWithDesc, Length: 361426, dtype: str

In [1637]:
#Combining the Non-collision and Not Applicable values in the MotorVehicleInvolvedWithDesc column into one value of Non-Collision since they are essentially the same thing. This will help with analysis later on
primary_collision_factor_violation_values_A.loc[primary_collision_factor_violation_values_A['MotorVehicleInvolvedWithDesc'] == 'NOT-APPLICABLE', 'MotorVehicleInvolvedWithDesc'] = 'NON-COLLISION'

In [1638]:
#Checking for the other Desc column for NaN values. If there are any, fill them in with N/A since it is a description column and should not be blank
primary_collision_factor_violation_values_A[(primary_collision_factor_violation_values_A['MotorVehicleInvolvedWithOtherDesc'] == '') | primary_collision_factor_violation_values_A['MotorVehicleInvolvedWithOtherDesc'].isna()]['MotorVehicleInvolvedWithOtherDesc']

0         NaN
1         NaN
2         NaN
4         NaN
5         NaN
         ...
393504    NaN
393505    NaN
393506    NaN
393507    NaN
393508    NaN
Name: MotorVehicleInvolvedWithOtherDesc, Length: 305009, dtype: str

In [1639]:
#Filling in any blank values in the MotorVehicleInvolvedWithOtherDesc column with N/A
primary_collision_factor_violation_values_A['MotorVehicleInvolvedWithOtherDesc'] = primary_collision_factor_violation_values_A['MotorVehicleInvolvedWithOtherDesc'].fillna('N/A')

In [1640]:
#Assert above is true
assert(primary_collision_factor_violation_values_A[(primary_collision_factor_violation_values_A['MotorVehicleInvolvedWithDesc'] == '') | primary_collision_factor_violation_values_A['MotorVehicleInvolvedWithDesc'].isna()]['MotorVehicleInvolvedWithDesc'].empty)

In [1641]:
primary_collision_factor_violation_values_A['MotorVehicleInvolvedWithOtherDesc'].value_counts()

MotorVehicleInvolvedWithOtherDesc
N/A                          305009
TREE                           3361
GUARDRAIL                      1797
CONCRETE WALL                  1665
FENCE                          1543
                              ...
FIRE HYDRANT #246                 1
CURB / FIRE HYDRANT / LIG         1
CURB(S) / TREE(S)                 1
LIGHT POST- CITY CURB             1
CITY SIGN/ CURB                   1
Name: count, Length: 9430, dtype: int64

In [1642]:
#Drop this column since a very large majority of the values are N/A and it will not be useful for analysis. It is also a description column and will not be useful for analysis
primary_collision_factor_violation_values_A = primary_collision_factor_violation_values_A.drop(['MotorVehicleInvolvedWithOtherDesc'], axis=1)

In [1643]:
primary_collision_factor_violation_values_A.rename(columns = {'Collision Id':'CollisionId'}, inplace = True)

In [1644]:
primary_collision_factor_violation_values_A.to_csv("main_collision_factors.csv", index = False)

In [1645]:
crash_parties_data

,_id,PartyId,CollisionId,PartyNumber,PartyType,IsAtFault,IsOnDutyEmergencyVehicle,IsHitAndRun,AirbagCode,AirbagDescription,...,Vehicle2TypeDesc,Vehicle2Year,Vehicle2Make,Vehicle2Model,Vehicle2Color,V2IsVehicleTowed,Lane,ThruLanes,TotalLanes,IsDREConducted
0,1,13900346,4541902,1,Driver,True,False,True,B,UNKNOWN,...,NaN,NaN,NaN,NaN,NaN,NaN,N/B,1.0,1.0,False
1,2,13900345,4541901,2,Driver,NaN,False,False,M,AIR BAG NOT DEPLOYED,...,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,5.0,False
2,3,13900344,4541901,1,Driver,True,False,False,L,AIR BAG DEPLOYED,...,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,5.0,False
3,4,13900343,4541900,2,Driver,NaN,False,False,M,AIR BAG NOT DEPLOYED,...,NaN,NaN,NaN,NaN,NaN,NaN,E/B,1.0,1.0,False
4,5,13900342,4541900,1,Driver,NaN,False,False,M,AIR BAG NOT DEPLOYED,...,NaN,NaN,NaN,NaN,NaN,NaN,N/B,1.0,1.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
767047,767048,14979609,5105674,1,Driver,True,False,NaN,M,AIR BAG NOT DEPLOYED,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1.0,1.0,NaN
767048,767049,14979608,5105673,1,Driver,True,False,NaN,M,AIR BAG NOT DEPLOYED,...,NaN,NaN,NaN,NaN,NaN,NaN,1,1.0,1.0,NaN
767049,767050,14979607,5105672,2,Driver,NaN,False,NaN,M,AIR BAG NOT DEPLOYED,...,NaN,NaN,NaN,NaN,NaN,NaN,1,3.0,3.0,NaN
767050,767051,14979606,5105672,1,Driver,True,False,NaN,M,AIR BAG NOT DEPLOYED,...,NaN,NaN,NaN,NaN,NaN,NaN,2,3.0,3.0,NaN
767051,767052,14979605,5105671,2,Driver,NaN,False,NaN,M,AIR BAG NOT DEPLOYED,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1646]:
#list of columns to look at since too many to show at once
crash_parties_data.columns

Index(['_id', 'PartyId', 'CollisionId', 'PartyNumber', 'PartyType',
       'IsAtFault', 'IsOnDutyEmergencyVehicle', 'IsHitAndRun', 'AirbagCode',
       'AirbagDescription', 'SafetyEquipmentCode',
       'SafetyEquipmentDescription', 'Special Information',
       'Other Associate Factor', 'Inattention', 'DirectionOfTravel',
       'StreetOrHighwayName', 'SpeedLimit', 'MovementPrecCollCode',
       'MovementPrecCollDescription', 'SobrietyDrugPhysicalCode1',
       'SobrietyDrugPhysicalDescription1', 'SobrietyDrugPhysicalCode2',
       'SobrietyDrugPhysicalDescription2', 'GenderCode', 'GenderDescription',
       'StatedAge', 'DriverLicenseClass', 'DriverLicenseStateCode', 'RaceCode',
       'RaceDesc', 'Vehicle1TypeId', 'Vehicle1TypeDesc', 'Vehicle1Year',
       'Vehicle1Make', 'Vehicle1Model', 'Vehicle1Color', 'V1IsVehicleTowed',
       'Vehicle2TypeId', 'Vehicle2TypeDesc', 'Vehicle2Year', 'Vehicle2Make',
       'Vehicle2Model', 'Vehicle2Color', 'V2IsVehicleTowed', 'Lane',
       'ThruLanes', 'TotalLanes', 'IsDREConducted'],
      dtype='str')

In [1647]:
#Drop the cars that are older than 1980 since they are not relevant to the analysis and will not be useful for analysis. This will also help with analysis later on since it will reduce the amount of data that needs to be analyzed
crash_parties_data.drop(crash_parties_data[crash_parties_data['Vehicle1Year'] < 1980].index,inplace = True)

In [1648]:
if crash_parties_data.duplicated().sum() > 0:
    dropped_duplicates_crash_parties_data = crash_parties_data.drop_duplicates() #drop any duplicate rows in the dataframe

In [1649]:
#crash_parties_data.dropna(subset = ['Vehicle2Year'],inplace = True)

In [1650]:
crash_parties_data['IsAtFault']

0         True
1          NaN
2         True
3          NaN
4          NaN
          ...
767047    True
767048    True
767049     NaN
767050    True
767051     NaN
Name: IsAtFault, Length: 765797, dtype: object

In [1651]:
#Check if there are any NaN values in the IsAtFault column. If there are, fill them in with False since it should only be True or False
crash_parties_data['IsAtFault'].isna().sum()

np.int64(402932)

In [1652]:
crash_parties_data['PartyType'].value_counts()

PartyType
Driver           682445
ParkedVehicle     54432
Pedestrian        13114
Bicyclist         11723
Other              3816
Operator            267
Name: count, dtype: int64

In [1653]:
#Check if there are any NaN values in the PartyType column. If there are, fill them in with Not Applicable since it is a description column and should not be blank
crash_parties_data['PartyType'].isna().sum()

np.int64(0)

In [1654]:
#This column is not useful to me since I do not have any knowledge of what the codes mean and it will not be useful for analysis. I will drop this column since it is not useful for analysis
crash_parties_data.drop('SafetyEquipmentCode', axis=1, inplace=True)

It seems that in about 80 percent of reported accidents, people do use their seatbelts.

In [1655]:
len(crash_parties_data['SafetyEquipmentDescription'])

765797

In [1656]:
crash_parties_data['SafetyEquipmentDescription'].value_counts()

SafetyEquipmentDescription
OCCUPANT LAP SHOULDER HARNESS USED         549632
OCCUPANT UNKNOWN                            46037
NOT REQUIRED                                13245
MOTOR BICYCLE DRIVER WITH HELMET            10668
OCCUPANT LAP BELT USED                       9588
OCCUPANT LAP SHOULDER HARNESS NOT USED       6789
OCCUPANT NONE IN VEHICLE                     5383
OCCUPANT SHOULDER HARNESS USED               3151
MOTOR BICYCLE DRIVER NO HELMET               2513
OCCUPANT SHOULDER HARNESS NOT USED           1331
OCCUPANT LAP BELT NOT USED                    741
OCCUPANT PASSIVE RESTRAINT USED               513
MOTOR BICYCLE PASSENGER WITH HELMET           199
CHILD IN VEHICLE USED                         124
MOTOR BICYCLE PASSENGER NO HELMET             120
OCCUPANT PASSIVE RESTRAINT NOT USED            62
CHILD IN VEHICLE USE UNKNOWN                   62
CHILD RESTRAINT NONE IN VEHICLE                56
CHILD IN VEHICLE NOT USED                      29
CHILD RESTRAINT IN VEHICLE IMPROPER_USE        16
AIR BAG DEPLOYED                               12
OTHER                                           1
Name: count, dtype: int64

In [1657]:
crash_parties_data['Special Information'].value_counts()

Special Information
CELL PHONE NOT IN USE                                  603107
CELL PHONE USE UNKNOWN                                  89882
CELL PHONE HANDHELD IN USE                               4944
CELL PHONE HANDSFREE IN USE                              3372
HAZARDOUS MATERIAL                                        589
CELL PHONE NOT IN USE / SCHOOL BUS RELATED                440
HAZARDOUS MATERIAL / CELL PHONE NOT IN USE                313
SCHOOL BUS RELATED                                        291
CELL PHONE USE UNKNOWN / SCHOOL BUS RELATED                46
CELL PHONE NOT IN USE / CELL PHONE USE UNKNOWN             46
HAZARDOUS MATERIAL / CELL PHONE USE UNKNOWN                20
CELL PHONE HANDSFREE IN USE / CELL PHONE NOT IN USE         7
HAZARDOUS MATERIAL / CELL PHONE HANDHELD IN USE             5
CELL PHONE HANDHELD IN USE / CELL PHONE NOT IN USE          3
HAZARDOUS MATERIAL / SCHOOL BUS RELATED                     3
HAZARDOUS MATERIAL / CELL PHONE HANDSFREE IN USE            2
CELL PHONE HANDHELD IN USE / CELL PHONE USE UNKNOWN         2
CELL PHONE HANDHELD IN USE / SCHOOL BUS RELATED             1
Name: count, dtype: int64

It seems that cell phone usage when driving might not be a reliable indicator for determing accidents.

In [1658]:
#This column is not useful to me since it does not give any useful information and will not be useful for analysis. I will drop this column since it is not useful for analysis
crash_parties_data['Other Associate Factor'].value_counts()

Other Associate Factor
NONE APPARENT                                                      647223
VC SECTION VIOLATED - VC 22107                                      10497
VC SECTION VIOLATED                                                 10163
INATTENTION                                                          8846
STOP & GO TRAFFIC                                                    8252
                                                                    ...
VC SECTION VIOLATED - 21651(a)(1) / OTHER                               1
VC SECTION VIOLATED - 14601.1(a) / NONE APPARENT                        1
VC SECTION VIOLATED - 23123(a) / INATTENTION                            1
VC SECTION VIOLATED - 23152(f) / NONE APPARENT                          1
VC SECTION VIOLATED - 26709(a)(1) / DEFECTIVE VEHICLE EQUIPMENT         1
Name: count, Length: 3653, dtype: int64

In [1659]:
crash_parties_data.drop('Other Associate Factor', axis=1, inplace=True)

In [1660]:
crash_parties_data['Inattention'].value_counts()

Inattention
OTHER                   6129
CELL PHONE HANDHELD     1200
CELL PHONE HANDSFREE     530
ELECTRONIC_EQUIPMENT     408
EATING                   343
RADIO/CD                 340
CHILDREN                 299
ANIMALS                  194
PERSONAL HYGIENE          56
SMOKING                   41
READING                   24
Name: count, dtype: int64

In [1661]:
crash_parties_data['Inattention'].isna().sum()

np.int64(756233)

It seems that people who are distracted when driving might be distracted by something in their enviornment (not cellphones, music, passengers). However it seems that it will not be useful since a lot of it is NA

In [1662]:
len(crash_parties_data['SpeedLimit'])

765797

In [1663]:
crash_parties_data['SpeedLimit'].value_counts().head(10)

SpeedLimit
65.0    211033
55.0     78802
25.0     71706
35.0     63725
45.0     43642
40.0     43167
30.0     16560
50.0     16534
70.0     14009
15.0      5830
Name: count, dtype: int64

In [1664]:
crash_parties_data['SpeedLimit'].value_counts().head(10).sum()

np.int64(565008)

In [1967]:
crash_parties_speed_limit_data = crash_parties_data[['CollisionId','SpeedLimit']]

In [1968]:
crash_parties_speed_limit_data.to_csv("crash_parties_speed_limit_data.csv", index = False)

It seems that the majority of accidents occur on streets ranging between 15-65 mph with nearly half being around roads on 55-65 mph road.

In [1665]:
#dividing into smaller sections to make handling easier
crash_parties_car_data = crash_parties_data[['CollisionId', 'Vehicle1Year',
       'Vehicle1Make', 'Vehicle1Model', 'Vehicle1Color', 'V1IsVehicleTowed']]

In [1666]:
Vehicle2 = crash_parties_data[['CollisionId', 'Vehicle2Year', 'Vehicle2Make', 'Vehicle2Model', 'Vehicle2Color', 'V2IsVehicleTowed']]

In [1667]:
#Renaming the columns in Vehicle2 to match the columns in crash_parties_car_data so that they can be combined later on. This will help with analysis later on since it will reduce the amount of data that needs to be analyzed
Vehicle2 = Vehicle2.rename(columns = {'Vehicle2Year': 'Vehicle1Year', 'Vehicle2Make': 'Vehicle1Make', 
                            'Vehicle2Model':'Vehicle1Model','Vehicle2Color':'Vehicle1Color','V2IsVehicleTowed' : 'V1IsVehicleTowed'})

In [1668]:
#Get a sense of what the data looks like in Vehicle2
Vehicle2

,CollisionId,Vehicle1Year,Vehicle1Make,Vehicle1Model,Vehicle1Color,V1IsVehicleTowed
0,4541902,NaN,NaN,NaN,NaN,NaN
1,4541901,NaN,NaN,NaN,NaN,NaN
2,4541901,NaN,NaN,NaN,NaN,NaN
3,4541900,NaN,NaN,NaN,NaN,NaN
4,4541900,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
767047,5105674,NaN,NaN,NaN,NaN,NaN
767048,5105673,NaN,NaN,NaN,NaN,NaN
767049,5105672,NaN,NaN,NaN,NaN,NaN
767050,5105672,NaN,NaN,NaN,NaN,NaN
767051,5105671,NaN,NaN,NaN,NaN,NaN

In [1669]:
Vehicle2['Vehicle1Year'].isna().sum()

np.int64(747685)

In [1670]:
Vehicle2['Vehicle1Make'].isna().sum()

np.int64(746585)

In [1671]:
#dropping a lot of the NaN rows since a very large majority of the values are NaN in the important columns
Vehicle2 = Vehicle2['Vehicle1Year'].dropna()

In [1672]:
#Make sure that there are still values in the Vehicle2 dataframe after dropping the NaN rows. If there are no values, then the analysis will not be useful since there will be no data to analyze
assert(len(Vehicle2)>0)

In [1673]:
crash_parties_car_data['V1IsVehicleTowed'].isna().sum()

np.int64(356641)

In [1674]:
#Combine the two dataframes crash_parties_car_data and Vehicle2 into one dataframe crash_parties_car_data. This will help with analysis later on since it will reduce the amount of data that needs to be analyzed
crash_parties_car_data = pd.concat([crash_parties_car_data, Vehicle2])

In [1675]:
crash_parties_car_data

,CollisionId,Vehicle1Year,Vehicle1Make,Vehicle1Model,Vehicle1Color,V1IsVehicleTowed
0,4541902.0,NaN,NaN,NaN,NaN,False
1,4541901.0,2005.0,FORD,F150,GRY,True
2,4541901.0,2002.0,FORD,TAURUS,GLD,True
3,4541900.0,2001.0,STRN,ION,GLD,False
4,4541900.0,2020.0,KIA,OPTIMA,WHI,False
...,...,...,...,...,...,...
766193,NaN,2024.0,NaN,NaN,NaN,NaN
766407,NaN,2025.0,NaN,NaN,NaN,NaN
766490,NaN,1995.0,NaN,NaN,NaN,NaN
766795,NaN,2022.0,NaN,NaN,NaN,NaN
766827,NaN,2024.0,NaN,NaN,NaN,NaN

In [1676]:
crash_parties_car_data['Vehicle1Make'] = crash_parties_car_data['Vehicle1Make'].str.upper().str.strip()

In [1677]:
crash_parties_car_data['Vehicle1Make'].value_counts().head(20)

Vehicle1Make
TOYT         71927
FORD         67610
TOYOTA       58558
HOND         47392
HONDA        41694
CHEV         30774
CHEVROLET    24593
NISS         23141
NISSAN       20935
KIA          20651
BMW          18155
GMC          14050
JEEP         13724
HYUN         11870
DODG         10687
DODGE        10415
LEXS         10249
HYUNDAI       9920
MERZ          9330
FRHT          8746
Name: count, dtype: int64

In [1678]:
crash_parties_car_data = crash_parties_car_data.replace(['TOYT','Toyota','PRUIS','SEQUIA','SEQUIOA', 'TOYOTA /', 
                                                         'TOYTA', 'TOYOA','TOYO','TOY','TOTY','TOTYA','TOYOT','TOYOTA TACOMA','TOYOTA015295',
                                                        'TOYOTAA','TOYOTOA','TOYOTQ','TOYOTS','TOYOYTA','TOYP','TOYT-TOYOTA','TOYTA','TOYTOA','TOYTT','TYOTA'
                                                        ],'TOYOTA')

In [1679]:
crash_parties_car_data = crash_parties_car_data.replace(['HOND','Honda','HONDA ODISSEY','HONDA /', 'HONA','HOINDA','HOND-HONDA','HONE'],'HONDA')

In [1680]:
crash_parties_car_data = crash_parties_car_data.replace(['CHEV','CHEVY','CHREVROLET','Chevrolet', 'CHEVROLET /','CEHVROLET','CHEV-CHEVROLET',
                                                         'CHEVERLOT','CHEVEROLET', 'CHEVORLET','CHEVRELOT','CHEVROLT','CHRVROLET','CHEVEROLET'],'CHEVROLET')

In [1681]:
crash_parties_car_data = crash_parties_car_data.replace(['NISS','Nissan'],'NISSAN')

In [1682]:
crash_parties_car_data = crash_parties_car_data.replace(['F0RD','F-150','FORD-FORD','FORSD'],'FORD')

In [1683]:
crash_parties_car_data = crash_parties_car_data.replace(['HYUN','HYUN - HYUNDAI','HYUNDAU'],'HYUNDAI')

In [1684]:
crash_parties_car_data = crash_parties_car_data.replace(['KIA MOTOR CORPORATION'],'KIA')

In [1685]:
crash_parties_car_data = crash_parties_car_data.replace(['DODG','DODGEDODG', 'DODGE /'],'DODGE')

In [1686]:
crash_parties_car_data = crash_parties_car_data.replace('LEXS','LEXUS')

In [1687]:
crash_parties_car_data = crash_parties_car_data.replace(['MERZ','MERCEDES','MERC','MERCEDEZ','MBZ', 'MERCEDES BENZ'],'MERCEDES-BENZ')

In [1688]:
crash_parties_car_data = crash_parties_car_data.replace('SUBA','SUBARU')

In [1689]:
crash_parties_car_data = crash_parties_car_data.replace(['MAZD','MADA'],'MAZDA')

In [1690]:
crash_parties_car_data = crash_parties_car_data.replace(['TESL','TSMR', 'TESLA MOTORS'],'TESLA')

In [1691]:
crash_parties_car_data = crash_parties_car_data.replace(['VOLK','VOLKSWAGON','VW'],'VOLKSWAGEN')

In [1692]:
crash_parties_car_data = crash_parties_car_data.replace('ACUR','ACURA')

In [1693]:
crash_parties_car_data = crash_parties_car_data.replace(['INFI','INFINITY'],'INFINITI')

In [1694]:
crash_parties_car_data = crash_parties_car_data.replace('VOLV','VOLVO')

In [1695]:
crash_parties_car_data = crash_parties_car_data.replace(['FRHT','PTRB','KW','FREIGHTLINER','MACK  TR  BLUE','MACK',
                                                         'PETERBILT','HINO','KENWORTH','PETERBUILT', 'PTBR', 'PTR', 'PB', 'PETERBILT MOTOR CO.', 'PERTERBILT', 'PETER'
                                                        'PENSKE'],'SEMI-TRUCK')

In [1696]:
crash_parties_car_data = crash_parties_car_data.replace(['CHRY','CHYRSLER','CHRYSTLER','CHRY - CHRYSLER','CRYSLER', 'CHRYS','CHYSLER'], 'CHRYSLER')

In [1697]:
crash_parties_car_data = crash_parties_car_data.replace(['JEEP (1989 AND LATER'], 'JEEP')

In [1698]:
crash_parties_car_data = crash_parties_car_data.replace('BUIC','BUICK')

In [1699]:
crash_parties_car_data = crash_parties_car_data.replace('CADI','CADILLAC')

In [1700]:
crash_parties_car_data = crash_parties_car_data.replace('HD','HARLEY DAVIDSON')

In [1701]:
crash_parties_car_data = crash_parties_car_data.replace(['MITS','MITSUBISH'],'MITSUBISHI')

In [1702]:
crash_parties_car_data = crash_parties_car_data.replace('YAMA','YAMAHA')

In [1703]:
crash_parties_car_data = crash_parties_car_data.replace(['SCIO','SION'],'SCION')

In [1704]:
crash_parties_car_data = crash_parties_car_data.replace('KAWK','KAWAKSAKI')

In [1705]:
crash_parties_car_data = crash_parties_car_data.replace('LNDR','LAND ROVER')

In [1706]:
crash_parties_car_data = crash_parties_car_data.replace('LINC','LINCOLN')

In [1707]:
crash_parties_car_data = crash_parties_car_data.replace(['MNNI','MINI'],'MINI COOPER')

In [1708]:
crash_parties_car_data = crash_parties_car_data.replace('SUZI','SUZUKI')

In [1709]:
crash_parties_car_data = crash_parties_car_data.replace(['FORD TAURUS','Ford','FORD ', 'FORD /'],'FORD')

In [1710]:
crash_parties_car_data = crash_parties_car_data.replace('PONT','PONTIAC')

In [1711]:
crash_parties_car_data = crash_parties_car_data.replace('STRN','SATURN')

In [1712]:
crash_parties_car_data = crash_parties_car_data.replace('JAGU','JAGUAR')

In [1713]:
crash_parties_car_data = crash_parties_car_data.replace('ISU','ISUZU')

In [1714]:
crash_parties_car_data = crash_parties_car_data.replace('PORS','PORSCHE')

In [1715]:
crash_parties_car_data = crash_parties_car_data.replace(['UTIL','UTILITY TRAILER','UTILI', 'STRIPER' ],'UTILITY')

In [1716]:
crash_parties_car_data = crash_parties_car_data.replace(['HUMMER','GENERAL MOTORS CORP.','HUMM'],'GMC')

In [1717]:
crash_parties_car_data = crash_parties_car_data.replace(['RIVI'],'RIVIAN')

In [1718]:
crash_parties_car_data = crash_parties_car_data.replace(['BLUEBIRD','BB','NEW FLYER','BLUE BIRD', 'OTHER - BUS', 'GILLIG (BUS)', 'GILLIG', 'NABI', 'THOB','GREAT DANE TRAILERS'], 'BUS')

In [1719]:
crash_parties_car_data = crash_parties_car_data.replace(['MASE'],'MASERATI')

In [1720]:
crash_parties_car_data = crash_parties_car_data.replace(['SCHWINN','BIKE'],'BICYCLE')

In [1721]:
crash_parties_car_data = crash_parties_car_data.replace(['WABASH'],'TRAIN')

In [1722]:
crash_parties_car_data = crash_parties_car_data.replace(['WANC', 'GREAT DANE','GDAN', 'UNK','HYTR', 'U','HYUNDAI TRANSLEAD TRAILER'],'TRAILER')

In [1723]:
crash_parties_car_data = crash_parties_car_data.replace(['INTL'],'INTERNATIONAL')

In [1724]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'M3') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'HONDA'), 'Vehicle1Make'] = 'BMW'

In [1725]:
crash_parties_car_data = crash_parties_car_data.replace('/', '')

In [1726]:
crash_parties_car_data['Vehicle1Make'].value_counts().head(50).sum()

np.int64(683691)

In [1727]:
crash_parties_car_data['Vehicle1Make'].value_counts().head(60)

Vehicle1Make
TOYOTA                     130759
HONDA                       89209
FORD                        67687
CHEVROLET                   56522
NISSAN                      44076
HYUNDAI                     21792
DODGE                       21126
KIA                         20750
TESLA                       19073
LEXUS                       18766
SEMI-TRUCK                  18573
BMW                         18156
MERCEDES-BENZ               17820
GMC                         14343
JEEP                        13725
SUBARU                      11811
MAZDA                       11582
VOLKSWAGEN                  11079
ACURA                        8634
RAM                          6508
AUDI                         6409
INFINITI                     6280
CHRYSLER                     5065
VOLVO                        4404
CADILLAC                     4275
BUICK                        2687
HARLEY DAVIDSON              2652
MITSUBISHI                   2632
INTERNATIONAL                2545
SCION                        2082
YAMAHA                       2061
UNKNOWN                      1897
LAND ROVER                   1854
LINCOLN                      1836
BUS                          1780
PORSCHE                      1680
MINI COOPER                  1644
SUZUKI                       1266
KAWAKSAKI                    1106
ISUZU                        1022
SATURN                        953
PONTIAC                       912
KAWASAKI                      777
JAGUAR                        746
HARLEY-DAVIDSON               655
TRAILER                       546
BICYCLE                       543
MIFU                          494
FIAT                          490
RIVIAN                        407
GENESIS                       363
MERCURY                       317
OTHER - AUTO                  272
MASERATI                      240
NFLYR                         239
KTM                           209
TREK                          204
SPECIALIZED                   185
AUTOCAR                       182
INTERNATIONAL HARVESTER       154
Name: count, dtype: int64

In [1728]:
crash_parties_car_data['Vehicle1Make'].value_counts()[60:120]

Vehicle1Make
ELDOR                  148
VC SECTION 20002(A)    135
POLARIS                135
DUCATI                 133
ALFA ROMEO             132
GNSI                   129
TRIU                   128
HUFFY                  127
THMS                   120
FREIGHT LINER          119
ALFA                   111
JOHN DEERE             111
POLESTAR               110
PIERCE                 109
OTHER - TRUCK          105
AUTC                   102
SEGWAY                 102
LUCID                  102
TRIUMPH                 98
GILG                    96
WESTERN STAR            95
ELECTRIC SCOOTER        95
OTHER - MOTORCYCLE      94
SMART                   84
NEWFLYER                83
GIANT                   80
ALFA ROMERO             80
E-SCOOTER               78
HIBOY                   76
EL DORADO               76
INDIAN                  75
GRUMMAN                 75
SURRON                  74
GILLI                   72
TALARIA                 68
SUPER 73                68
CAN-AM                  67
NINEBOT                 65
CANNONDALE              65
OLDSMOBILE              65
ELDORADO                64
KME                     62
SCOOTER                 62
WSTR                    60
NFLY                    59
SAA                     58
MONGOOSE                58
MCI                     56
GOTRAX                  56
RANGE ROVER             55
GEO                     54
VESPA                   53
ELDO                    52
OLDS                    51
BYD                     48
AVENTON                 48
WINNEBAGO               47
TRUM                    47
WHITE                   47
JETSON                  46
Name: count, dtype: int64

In [1729]:
crash_parties_car_data.loc[crash_parties_car_data['Vehicle1Year'] > 2026, 'Vehicle1Year'] = 2025

In [1730]:
crash_parties_car_data.loc[crash_parties_car_data['Vehicle1Year'] > 2026, 'Vehicle1Year'] = 2025

In [1731]:
crash_parties_car_data['Vehicle1Model'].value_counts()[51:100]

Vehicle1Model
FORESTER          2048
GRAND CHEROKEE    1923
SOUL              1875
2500              1848
RX350             1831
CAMARO            1829
SUBURBAN          1827
COLORADO          1820
SORENTO           1766
CX-5              1731
CRUZE             1708
MDX               1688
RAM 1500 PU       1678
TRAVERSE          1658
CHALLENGER        1652
DURANGO           1650
EDGE              1625
TRANSIT           1616
SANTA FE          1568
F350              1539
AVALON            1527
PATHFINDER        1519
FIT               1509
CROSSTREK         1508
EXPEDITION        1504
328I              1409
SPORTAGE          1367
TL                1362
ES350             1335
C300              1321
300               1277
IMPALA            1239
YARIS             1226
IS250             1201
X5                1155
EXPRESS           1155
MAZDA3            1143
RAM               1127
X3                1111
COMPASS           1096
G35               1076
IMPREZA           1069
ESCALADE          1046
BUS               1042
E350              1041
4RUNNER           1008
ES300              999
ACCENT             999
TUSCON             992
Name: count, dtype: int64

In [1732]:
crash_parties_car_data['Vehicle1Model'] = crash_parties_car_data['Vehicle1Model'].str.upper().str.strip()

In [1733]:
crash_parties_car_data = crash_parties_car_data.replace(['3','Model 3', 'MODEL 3 '],'MODEL 3')

In [1734]:
crash_parties_car_data = crash_parties_car_data.replace(['Y', 'Model Y', 'MODEL Y ', 'Y SERIES'], 'MODEL Y')

In [1735]:
crash_parties_car_data = crash_parties_car_data.replace(['CR-V'], 'CRV')

In [1736]:
crash_parties_car_data = crash_parties_car_data.replace(['F150'], 'F-150')

In [1737]:
crash_parties_car_data = crash_parties_car_data.replace(['F250'], 'F-250')

In [1738]:
crash_parties_car_data = crash_parties_car_data.replace(['RAM 1500 PU', '1500'], 'RAM 1500')

In [1739]:
crash_parties_car_data = crash_parties_car_data.replace(['RAM 2500 PU', '2500', '2500 HD'], 'RAM 2500')

In [1740]:
crash_parties_car_data = crash_parties_car_data.replace(['RAM 3500 PU', '3500'], 'RAM 3500')

In [1741]:
crash_parties_car_data = crash_parties_car_data.replace(['RAV-4', 'RAV4 HYBRID', 'Rav 4', 'RAV 4', 'RAV'], 'RAV4')

In [1742]:
crash_parties_car_data = crash_parties_car_data.replace(['4RUNNER', '4 RUNNER', '4 Runner', '4-Runner ', '4-Runner', '4RN' ], '4-RUNNER')

In [1743]:
crash_parties_car_data = crash_parties_car_data.replace(['S','s', 'Model S'], 'MODEL S')

In [1744]:
crash_parties_car_data = crash_parties_car_data.replace(['  CASCADIA', ' CASCADIA'], 'CASCADIA')

In [1745]:
crash_parties_car_data = crash_parties_car_data.replace(['MAZDA 3'], 'MAZDA3')

In [1746]:
crash_parties_car_data = crash_parties_car_data.replace(['X'], 'MODEL X')

In [1747]:
crash_parties_car_data = crash_parties_car_data.replace(['Civic','CIVIC (AND CRX)', ' CIVIC'], 'CIVIC')

In [1748]:
crash_parties_car_data = crash_parties_car_data.replace(['Accord', ' Accord', ' ACCORD'], 'ACCORD')

In [1749]:
crash_parties_car_data = crash_parties_car_data.replace(['Camry', ' Camry', ' CAMRY','CAM','CAMARY','CAMRY 4D', 'CAMRY /', 'CAMRY SE'], 'CAMRY')

In [1750]:
crash_parties_car_data = crash_parties_car_data.replace(['Corolla','COA'], 'COROLLA')

In [1751]:
crash_parties_car_data = crash_parties_car_data.replace(['HGH', 'HHR'], 'HIGHLANDER')

In [1752]:
crash_parties_car_data = crash_parties_car_data.replace(['SNA','VAN'], 'SIENNA')

In [1753]:
crash_parties_car_data = crash_parties_car_data.replace(['PRI', 'Prius'], 'PRIUS')

In [1754]:
crash_parties_car_data = crash_parties_car_data.replace(['ES300H'], 'ES300')

In [1755]:
crash_parties_car_data = crash_parties_car_data.replace(['Silverado'], 'SILVERADO')

In [1756]:
crash_parties_car_data = crash_parties_car_data.replace(['Tacoma', 'TAC'], 'TACOMA')

In [1757]:
crash_parties_car_data = crash_parties_car_data.replace(['TUN'], 'TUNDRA')

In [1758]:
crash_parties_car_data = crash_parties_car_data.replace(['M-3', '3 Series','330I','328I','325I','330CI','320I','335I', '330', '340I'], '3 SERIES')

In [1759]:
crash_parties_car_data = crash_parties_car_data.replace(['F550'], 'F-550')

In [1760]:
crash_parties_car_data = crash_parties_car_data.replace(['F350'], 'F-350')

In [1761]:
crash_parties_car_data = crash_parties_car_data.replace(['Ariya'], 'ARIYA')

In [1762]:
crash_parties_car_data = crash_parties_car_data.replace(['IONIQ5'], 'IONIQ 5')

In [1763]:
crash_parties_car_data = crash_parties_car_data.replace(['TRUCK TRACTOR- GASOLINE', 'TRUCK TRACTOR- DIESEL'], 'TRUCK TRACTOR')

In [1764]:
crash_parties_car_data = crash_parties_car_data.replace(['BIKE'], 'BICYCLE')

In [1765]:
crash_parties_car_data = crash_parties_car_data.replace(['IONIC'], 'IONIQ')

In [1766]:
crash_parties_car_data = crash_parties_car_data.replace(['TOWN AND COUNTRY'], 'TOWN & COUNTRY')

In [1767]:
crash_parties_car_data = crash_parties_car_data.replace(['ID .4', 'ID.4'], 'ID4')

In [1768]:
crash_parties_car_data = crash_parties_car_data.replace(['F450'], 'F-450')

In [1769]:
crash_parties_car_data = crash_parties_car_data.replace(['MAZDA 6', 'MAZDA 6 '], 'MAZDA6')

In [1770]:
crash_parties_car_data = crash_parties_car_data.replace(['CAYENNE S'], 'CAYENNE')

In [1771]:
crash_parties_car_data = crash_parties_car_data.replace(['E-350', 'ECONOLINE E350'], 'ECONOLINE E350')

In [1772]:
crash_parties_car_data = crash_parties_car_data.replace(['CYBER TRUCK' ], 'CYBERTRUCK')

In [1773]:
crash_parties_car_data = crash_parties_car_data.replace(['IS 250', 'IS200T' ], 'IS250')

In [1774]:
crash_parties_car_data = crash_parties_car_data.replace(['SEMITRUCK','SEMI', 'FTL', 'FREIGHTLNR', 'FRT', 'INTERNATIONAL', 'KRMCT', 'PENSKE' ], 'SEMI-TRUCK')

In [1775]:
crash_parties_car_data = crash_parties_car_data.replace(['HRV'], 'HR-V')

In [1776]:
crash_parties_car_data = crash_parties_car_data.replace(['CHR'], 'CH-R')

In [1777]:
crash_parties_car_data = crash_parties_car_data.replace(['C-CLASS'], 'C350')

In [1778]:
crash_parties_car_data = crash_parties_car_data.replace(['CMAX'], 'C-MAX')

In [1779]:
crash_parties_car_data = crash_parties_car_data.replace(['RX450H'], 'RX450')

In [1780]:
crash_parties_car_data = crash_parties_car_data.replace(['NX350H'], 'NX350')

In [1781]:
crash_parties_car_data = crash_parties_car_data.replace(['UTILITY TRAILER', 'BOX TRAILER', 'SEMI TRAILER', 'DUMP TRAILER', 'FLATBED TRAILER', 'TANK TRAILER', 'TRLR'], 'TRAILER')

In [1782]:
crash_parties_car_data = crash_parties_car_data.replace(['DUMP'],'DUMP TRUCK')

In [1783]:
crash_parties_car_data = crash_parties_car_data.replace(['300, CHRYSLER 300', '300 Series'],'300 SERIES')

In [1784]:
crash_parties_car_data = crash_parties_car_data.replace(['GLE 350'],'GLE350')

In [1785]:
crash_parties_car_data = crash_parties_car_data.replace(['X-TERRA'],'XTERRA')

In [1786]:
crash_parties_car_data = crash_parties_car_data.replace(['CX30'],'CX-30')

In [1787]:
crash_parties_car_data = crash_parties_car_data.replace(['CX50'],'CX-50')

In [1788]:
crash_parties_car_data = crash_parties_car_data.replace(['GLC300'],'GLC 300')

In [1789]:
crash_parties_car_data = crash_parties_car_data.replace(['KICK'],'KICKS')

In [1790]:
crash_parties_car_data = crash_parties_car_data.replace(['R1 S', 'RS1', 'R15','RIS','R1S ADVENTURE', 'RS','R1-S','S1','R2S','RS-1','R/S'],'R1S')

In [1791]:
crash_parties_car_data = crash_parties_car_data.replace(['R17', 'R1F', 'R1 T', 'RT1','R IT', 'RIVIAN R1T','T1','R1T LAUNCH EDITION', 'R-1T', 'RIT'],'R1T')

In [1792]:
crash_parties_car_data = crash_parties_car_data.replace(['SCHOOL BUS'],'BUS') #Putting together the Bus categories

In [1793]:
crash_parties_car_data = crash_parties_car_data.replace(['NINJA'],'MOTORCYCLE') #Putting together the Bus categories

In [1794]:
crash_parties_car_data = crash_parties_car_data.replace(['EXPRESS', 'SPRINTER', 'TRANSIT 350', 'EDV 700', 'EDV TRIM 700', 'EDV','TRANSPORT', 
                                                         'RCV','AMAZON','EDV700', 'CARAVAN', 'EDU700','700', 'UTILY','U-HAUL'],'UTILITY VAN') 
#EXPRESS Vehicles are essentially those white utility vans

In [1795]:
crash_parties_car_data = crash_parties_car_data.replace('MRAI','Mirai') 
#EXPRESS Vehicles are essentially those white utility vans

In [1796]:
crash_parties_car_data = crash_parties_car_data.replace(['S-10'],'S10') #EXPRESS Vehicles are essentially those white utility vans

In [1797]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == '6') 
                            & (crash_parties_car_data['Vehicle1Make'] == 'TESLA'), 'Vehicle1Model'] = 'MODEL 3'

In [1798]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == '6') 
                            & (crash_parties_car_data['Vehicle1Make'] == 'MAZDA'), 'Vehicle1Model'] = 'MAZDA6'

In [1799]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == '300') 
                            & (crash_parties_car_data['Vehicle1Make'] == 'CHRYSLER'), 'Vehicle1Model'] = '300 Series'

In [1800]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == '300') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'LEXUS') & 
                            (crash_parties_car_data['Vehicle1Year'] > 2016), 'Vehicle1Model'] = 'IS300'

In [1801]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == '300') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'LEXUS')&
                            (crash_parties_car_data['Vehicle1Year'] < 2001), 'Vehicle1Model'] = 'RX300'

In [1802]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == '300') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'LEXUS')&
                            (crash_parties_car_data['Vehicle1Year'] > 2003), 'Vehicle1Model'] = 'IS300'

In [1803]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == '300') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'LEXUS'),'Vehicle1Model'] = 'IS300'

In [1804]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == '200') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'LEXUS'),'Vehicle1Model'] = 'IS200'

In [1805]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == '200') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'BMW'),'Vehicle1Model'] = '2 SERIES'

In [1806]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == '200') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'CHEVROLET'),'Vehicle1Make'] = 'CHRYSLER'

In [1807]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == '300') &
                            (crash_parties_car_data['Vehicle1Make'] == 'MERCEDES-BENZ'), 'Vehicle1Model'] = 'C300'

In [1808]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'M3') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'TESLA'), 'Vehicle1Model'] = 'MODEL 3'

In [1809]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'M3') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'BMW'), 'Vehicle1Model'] = '3 SERIES'

In [1810]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'M3') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'MAZDA'), 'Vehicle1Model'] = 'MAZDA3'

In [1811]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'].isin(['PICK UP', 'PICKUP']))  & 
                            (crash_parties_car_data['Vehicle1Make'] == 'TOYOTA'), 'Vehicle1Model'] = 'TACOMA' #Labeling it as Tacoma since it seems that pick up trucks are smaller

In [1812]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'TRUCK') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'TOYOTA'), 'Vehicle1Model'] = 'TACOMA' #Labeling it as Tacoma since it seems that pick up trucks are smaller

In [1813]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'PICK UP') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'GMC'),'Vehicle1Model'] = 'Sierra' #Labeling it as Sierra since it was most popular GMC truck in this class

In [1814]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'TRUCK') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'GMC'),'Vehicle1Model'] = 'Sierra' #Labeling it as Sierra since it was most popular GMC truck in this class

In [1815]:
crash_parties_car_data.drop(crash_parties_car_data[
                            (crash_parties_car_data['Vehicle1Model'] == 'PICK UP') & 
                            crash_parties_car_data['Vehicle1Year'].isna() & 
                            crash_parties_car_data['Vehicle1Make'].isna()].index, inplace = True)

In [1816]:
crash_parties_car_data.drop(crash_parties_car_data[(crash_parties_car_data['Vehicle1Model'] == 'PICK UP') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'UNKNOWN')].index, inplace = True)

In [1817]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'PICK UP') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'RAM'), 'Vehicle1Model'] = 'RAM 1500'

In [1818]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'TRUCK') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'RAM'), 'Vehicle1Model'] = 'RAM 1500'

In [1819]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'].isin (['PICK UP', 'PICKUP'])) &
                            (crash_parties_car_data['Vehicle1Make'] == 'NISSAN'), 'Vehicle1Model'] = 'FRONTIER'

In [1820]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'TRUCK') &
                            (crash_parties_car_data['Vehicle1Make'] == 'NISSAN'), 'Vehicle1Model'] = 'FRONTIER'

In [1821]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'PICK UP') &
                            (crash_parties_car_data['Vehicle1Make'] == 'CHEVROLET'), 'Vehicle1Model'] = 'SILVERADO'

In [1822]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'TRUCK') &
                            (crash_parties_car_data['Vehicle1Make'] == 'CHEVROLET'), 'Vehicle1Model'] = 'SILVERADO'

In [1823]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'PICK UP') &
                            (crash_parties_car_data['Vehicle1Make'] == 'FORD'), 'Vehicle1Model'] = 'F-150'

In [1824]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'TRUCK') &
                            (crash_parties_car_data['Vehicle1Make'] == 'FORD'), 'Vehicle1Model'] = 'F-150'

In [1825]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'PICK UP') &
                            (crash_parties_car_data['Vehicle1Make'] == 'DODGE'), 'Vehicle1Model'] = 'RAM 1500'

In [1826]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'TRUCK') &
                            (crash_parties_car_data['Vehicle1Make'] == 'DODGE'), 'Vehicle1Model'] = 'RAM 1500'

In [1827]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'TRUCK') &
                            (crash_parties_car_data['Vehicle1Make'] == 'JEEP'), 'Vehicle1Model'] = 'GLADIATOR'

In [1828]:
crash_parties_car_data.drop(crash_parties_car_data[(crash_parties_car_data['Vehicle1Model'] == 'PICK UP') & (crash_parties_car_data['Vehicle1Make'] == 'MAZDA')].index,inplace = True)

In [1829]:
crash_parties_car_data.drop(crash_parties_car_data[
                            (crash_parties_car_data['Vehicle1Model'] == 'UNKNOWN') ].index, inplace = True) # Would take too long to cross reference all 900 rows for what car they are based on just make

In [1830]:
crash_parties_car_data.drop(crash_parties_car_data[
                            (crash_parties_car_data['Vehicle1Model'] == 'UNKNOWN') ].index, inplace = True) # Would take too long to cross reference all 900 rows for what car they are based on just make

In [1831]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == '579') & (crash_parties_car_data['Vehicle1Make'] == 'SEMI-TRUCK'),'Vehicle1Model'] = 'SEMI-TRUCK'

In [1832]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == '389') & (crash_parties_car_data['Vehicle1Make'] == 'SEMI-TRUCK'),'Vehicle1Model'] = 'SEMI-TRUCK'

In [1833]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == '3 AXLE') & (crash_parties_car_data['Vehicle1Make'] == 'TRAILER'),'Vehicle1Model'] = 'TRAILER'

In [1834]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == '3 AXLE') & (crash_parties_car_data['Vehicle1Make'] == 'SEMI-TRUCK'),'Vehicle1Model'] = 'SEMI-TRUCK'

In [1835]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == '3 AXLE'), 'Vehicle1Model'] = 'SEMI-TRUCK' #Three wheel vehicles appear to be mainly semi trucks

In [1836]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == '3AXLE'), 
'Vehicle1Model'] = 'SEMI-TRUCK' #Three wheel vehicles appear to be mainly semi trucks

In [1837]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'TRUCK') & (crash_parties_car_data['Vehicle1Make'] == 'ROGU'), 'Vehicle1Model'] = 'DUMP TRUCK'

In [1838]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'TRUCK') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'KME'), 'Vehicle1Model'] = 'Fire Truck'

In [1839]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'TRUCK') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'PIERCE'), 'Vehicle1Model'] = 'Fire Truck'

In [1840]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'TRUCK') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'FRIE'), 'Vehicle1Model'] = 'Fire Truck'

In [1841]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'TRUCK') & (crash_parties_car_data['Vehicle1Make'] == 'SEMI-TRUCK'), 'Vehicle1Model'] = 'SEMI-TRUCK'

In [1842]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'TRUCK') & (crash_parties_car_data['Vehicle1Make'] == 'VOLVO'), 'Vehicle1Model'] = 'SEMI-TRUCK'

In [1843]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'TRUCK') & (crash_parties_car_data['Vehicle1Make'] == 'TESLA'), 'Vehicle1Model'] = 'CYBERTRUCK'

In [1844]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'TRUCK') & (crash_parties_car_data['Vehicle1Make'] == 'ISUZU'), 'Vehicle1Model'] = 'BOX TRUCK'

In [1845]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'TRUCK') & (crash_parties_car_data['Vehicle1Make'] == 'UTILITY'), 'Vehicle1Model'] = 'UTILITY VAN'

In [1846]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                                                    (crash_parties_car_data['Vehicle1Make'] == 'RIVIAN'), 'Vehicle1Model'] = 'R1S'

In [1847]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'PICKUP') & 
                                                    (crash_parties_car_data['Vehicle1Make'] == 'RIVIAN'), 'Vehicle1Model'] = 'R1T'

In [1848]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'PICK UP') & 
                                                    (crash_parties_car_data['Vehicle1Make'] == 'RIVIAN'), 'Vehicle1Model'] = 'R1T'

In [1849]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'PICK  UP') & 
                                                    (crash_parties_car_data['Vehicle1Make'] == 'RIVIAN'), 'Vehicle1Model'] = 'R1T'

In [1850]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'TRUCK') & 
                                                    (crash_parties_car_data['Vehicle1Make'] == 'RIVIAN'), 'Vehicle1Model'] = 'R1T'

In [1851]:
crash_parties_car_data.drop(crash_parties_car_data[(crash_parties_car_data['Vehicle1Make'] == 'RIVIAN') &
                              (crash_parties_car_data['Vehicle1Model'].isna())].index, inplace = True)

In [1852]:
crash_parties_car_data.drop(crash_parties_car_data[(crash_parties_car_data['Vehicle1Make'] == 'RIVIAN') & 
                            ((crash_parties_car_data['Vehicle1Model'] != 'R1S') &  
                             (crash_parties_car_data['Vehicle1Model'] != 'R1T') & 
                             (crash_parties_car_data['Vehicle1Model'] != 'VAN'))].index, inplace = True)

In [1853]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'TRUCK'), 'Vehicle1Model'] = 'SEMITRUCK'

In [1854]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'ES')]

,CollisionId,Vehicle1Year,Vehicle1Make,Vehicle1Model,Vehicle1Color,V1IsVehicleTowed
3707,4537890.0,2022.0,LEXUS,ES,White,NaN
11928,4549249.0,2020.0,LEXUS,ES,BLK,False
15310,4546079.0,2009.0,LEXUS,ES,WHI,False
19287,4542796.0,2008.0,LEXUS,ES,BLACK,NaN
20136,4561789.0,2007.0,LEXUS,ES,BLU,NaN
...,...,...,...,...,...,...
749883,5037294.0,2014.0,LEXUS,ES,WHI,False
750959,5105117.0,2011.0,LEXUS,ES,WHITE,NaN
755972,5075819.0,2022.0,LEXUS,ES,WHI,False
763877,5115955.0,2018.0,LEXUS,ES,NaN,NaN
765746,5110178.0,NaN,LIME,ES,GRY,NaN

In [1855]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == '2 AXLE') & 
                            ((crash_parties_car_data['Vehicle1Make'] == 'SEMI-TRUCK') | (crash_parties_car_data['Vehicle1Make'] == 'VOLVO')), 
                             'Vehicle1Model'] = 'SEMI-TRUCK'

In [1856]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == '2 AXLE') & 
                            ((crash_parties_car_data['Vehicle1Make'] == 'TRAILER')), 
                             'Vehicle1Model'] = 'TRAILER'

In [1857]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == '2 AXLE') & 
                            ((crash_parties_car_data['Vehicle1Make'] == 'TRAILER')), 
                             'Vehicle1Model'] = 'TRAILER'

In [1858]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == '2 AXLE') & 
                            ((crash_parties_car_data['Vehicle1Make'] == 'UTILITY')), 
                             'Vehicle1Model'] = 'UTILITY VAN'

In [1859]:
crash_parties_car_data.drop(crash_parties_car_data[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            ((crash_parties_car_data['Vehicle1Make'].isna()) | 
                             (crash_parties_car_data['Vehicle1Make'] == 'UNKNOWN') |  
                            (crash_parties_car_data['Vehicle1Make'] == 'HIT & RUN VEHICLE'))].index, inplace = True)

In [1860]:
crash_parties_car_data.drop(crash_parties_car_data[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            crash_parties_car_data['Vehicle1Year'].isna()].index, inplace = True)

In [1861]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'TOYOTA'), 'Vehicle1Model'] = 'RAV4'

In [1862]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'TESLA') & 
                            (crash_parties_car_data['Vehicle1Year'] < 2020), 'Vehicle1Model'] = 'MODEL X'

In [1863]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'HONDA'), 'Vehicle1Model'] = 'CRV'

In [1864]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'FORD'), 'Vehicle1Model'] = 'EXPLORER'

In [1865]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'NISSAN'), 'Vehicle1Model'] = 'ROGUE'

In [1866]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'MAZDA'), 'Vehicle1Model'] = 'CX-5'

In [1867]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'JEEP'), 'Vehicle1Model'] = 'WRANGLER'

In [1868]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'ACURA'), 'Vehicle1Model'] = 'MDX'

In [1869]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'CHEVROLET'), 'Vehicle1Model'] = 'EQUINOX'

In [1870]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'BMW'), 'Vehicle1Model'] = 'X5'

In [1871]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'LEXUS'), 'Vehicle1Model'] = 'RX350'

In [1872]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'HYUNDAI'), 'Vehicle1Model'] = 'SANTA FE'

In [1873]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'KIA'), 'Vehicle1Model'] = 'SORENTO'

In [1874]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'AUDI'), 'Vehicle1Model'] = 'Q5'

In [1875]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'MERCEDES-BENZ'), 'Vehicle1Model'] = 'GLC 300'

In [1876]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'LAND ROVER'), 'Vehicle1Model'] = 'DEFENDER'

In [1877]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'CADILLAC'), 'Vehicle1Model'] = 'ESCALADE'

In [1878]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'SUBARU'), 'Vehicle1Model'] = 'CROSSTREK'

In [1879]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'VOLKSWAGEN'), 'Vehicle1Model'] = 'TIGUAN'

In [1880]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'BUICK'), 'Vehicle1Model'] = 'ENCORE'

In [1881]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'INFINITI'), 'Vehicle1Model'] = 'QX60'

In [1882]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'PORSCHE'), 'Vehicle1Model'] = 'CAYENNE'

In [1883]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'MITSUBISHI'), 'Vehicle1Model'] = 'OUTLANDER'

In [1884]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'VOLVO'), 'Vehicle1Model'] = 'XC90'

In [1885]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'GMC'), 'Vehicle1Model'] = 'YUKON'

In [1886]:
crash_parties_car_data.drop(crash_parties_car_data[(crash_parties_car_data['Vehicle1Model'] == 'SUV') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'LINCOLN')].index, inplace = True) #dropping Lincoln SUVs since there is not any existing records in the top 500

In [1887]:
crash_parties_car_data.drop(crash_parties_car_data[(crash_parties_car_data['Vehicle1Model'] == 'SUV')].index, inplace = True) #MIFU doesnt make suvs

In [1888]:
crash_parties_car_data.drop(crash_parties_car_data[(crash_parties_car_data['Vehicle1Model'] == '2 AXLE')].index, inplace = True) #dropping the 2 Axle records since its a small amount of rows, it is not important if they get dropped

In [1889]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'ES') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'LEXUS') & 
                            (crash_parties_car_data['Vehicle1Year'] < 2006), 'Vehicle1Model'] = 'ES300'

In [1890]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'ES') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'LEXUS') & 
                            (crash_parties_car_data['Vehicle1Year'] >= 2006), 'Vehicle1Model'] = 'ES350'

In [1891]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'CIVIC') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'TOYOTA'), 'Vehicle1Make'] = 'HONDA'

In [1892]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'].isna()) & 
                            (crash_parties_car_data['Vehicle1Make'] == 'TOYOTA')&
                            (crash_parties_car_data['Vehicle1Year'] == 2006)]

,CollisionId,Vehicle1Year,Vehicle1Make,Vehicle1Model,Vehicle1Color,V1IsVehicleTowed
10522,4550524.0,2006.0,TOYOTA,NaN,NaN,NaN
10657,4550404.0,2006.0,TOYOTA,NaN,NaN,NaN
17605,4544170.0,2006.0,TOYOTA,NaN,NaN,NaN
17674,4544131.0,2006.0,TOYOTA,NaN,NaN,NaN
22120,4557751.0,2006.0,TOYOTA,NaN,NaN,NaN
...,...,...,...,...,...,...
756627,5072393.0,2006.0,TOYOTA,NaN,NaN,NaN
758318,5069580.0,2006.0,TOYOTA,NaN,NaN,NaN
759763,5065249.0,2006.0,TOYOTA,NaN,NaN,NaN
765529,5111649.0,2006.0,TOYOTA,NaN,NaN,NaN
765563,5111315.0,2006.0,TOYOTA,NaN,NaN,NaN

In [1893]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'CAMRY') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'TESLA')]

,CollisionId,Vehicle1Year,Vehicle1Make,Vehicle1Model,Vehicle1Color,V1IsVehicleTowed
223573,4689465.0,2022.0,TESLA,CAMRY,WHI,False

In [1894]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'MODEL 3') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'TESLA') &
                            (crash_parties_car_data['Vehicle1Year'] < 2017), 'Vehicle1Model'] = 'MODEL S'

In [1895]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'MODEL Y') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'TESLA') &
                            (crash_parties_car_data['Vehicle1Year'] < 2020), 'Vehicle1Model'] = 'MODEL X'

In [1896]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'MODEL 3') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'TESLA') &
                            (crash_parties_car_data['Vehicle1Year'] < 2017)]

Empty DataFrame
Columns: [CollisionId, Vehicle1Year, Vehicle1Make, Vehicle1Model, Vehicle1Color, V1IsVehicleTowed]
Index: []

In [1897]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'MODEL Y') & 
                            (crash_parties_car_data['Vehicle1Make'] == 'TESLA') &
                            (crash_parties_car_data['Vehicle1Year'] < 2020)]

Empty DataFrame
Columns: [CollisionId, Vehicle1Year, Vehicle1Make, Vehicle1Model, Vehicle1Color, V1IsVehicleTowed]
Index: []

In [1898]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'PRIUS') & 
                            (crash_parties_car_data['Vehicle1Make'] != 'TOYOTA'), 'Vehicle1Make'] = 'TOYOTA'

In [1899]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'CAMRY') & 
                            (crash_parties_car_data['Vehicle1Make'] != 'TOYOTA'), 'Vehicle1Make'] = 'TOYOTA'

In [1900]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'COROLLA') & 
                            (crash_parties_car_data['Vehicle1Make'] != 'TOYOTA'), 'Vehicle1Make'] = 'TOYOTA'

In [1901]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'RAV4') & 
                            (crash_parties_car_data['Vehicle1Make'] != 'TOYOTA'), 'Vehicle1Make'] = 'TOYOTA'

In [1902]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'ACCORD') & 
                            (crash_parties_car_data['Vehicle1Make'] != 'HONDA'), 'Vehicle1Make'] = 'HONDA'

In [1903]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'CIVIC') & 
                            (crash_parties_car_data['Vehicle1Make'] != 'HONDA'), 'Vehicle1Make'] = 'HONDA'

In [1904]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'ACCORD') & 
                            (crash_parties_car_data['Vehicle1Make'] != 'HONDA'), 'Vehicle1Make'] = 'HONDA'

In [1905]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SILVERADO') & 
                            (crash_parties_car_data['Vehicle1Make'] != 'CHEVROLET'), 'Vehicle1Make'] = 'CHEVROLET'

In [1906]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'].isin(['F-150','FUSION', 'C-MAX'])) & 
                            (crash_parties_car_data['Vehicle1Make'] != 'FORD'), 'Vehicle1Make'] = 'FORD'

In [1907]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'CRV') & 
                            (crash_parties_car_data['Vehicle1Make'] != 'HONDA'), 'Vehicle1Make'] = 'HONDA'

In [1908]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'].isin( ['ALTIMA','ROGUE'])) & 
                            (crash_parties_car_data['Vehicle1Make'] != 'NISSAN'), 'Vehicle1Make'] = 'NISSAN'

In [1909]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'SIERRA') & 
                            (crash_parties_car_data['Vehicle1Make'] != 'GMC'), 'Vehicle1Make'] = 'GMC'

In [1910]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'MODEL 3') & 
                            (crash_parties_car_data['Vehicle1Make'] != 'TESLA'), 'Vehicle1Make'] = 'TESLA'

In [1911]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'MODEL Y') & 
                            (crash_parties_car_data['Vehicle1Make'] != 'TESLA'), 'Vehicle1Make'] = 'TESLA'

In [1912]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'RAM 1500') & 
                            (crash_parties_car_data['Vehicle1Make'] != 'RAM'), 'Vehicle1Make'] = 'RAM'

In [1913]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'].isin( ['MPV'])) & 
                            (crash_parties_car_data['Vehicle1Make'] != 'RAM'), 'Vehicle1Make'] = 'RAM'

In [1914]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'ELANTRA') & 
                            (crash_parties_car_data['Vehicle1Make'] != 'HYUNDAI'), 'Vehicle1Make'] = 'HYUNDAI'

In [1915]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'HIGHLANDER') & 
                            (crash_parties_car_data['Vehicle1Make'] != 'TOYOTA'), 'Vehicle1Make'] = 'TOYOTA'

In [1916]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'TACOMA') & 
                            (crash_parties_car_data['Vehicle1Make'] != 'TOYOTA'), 'Vehicle1Make'] = 'TACOMA'

In [1917]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'].isin(['PILOT','MDX','ODSSEY'])) & 
                            (crash_parties_car_data['Vehicle1Make'] != 'HONDA'), 'Vehicle1Make'] = 'HONDA'

In [1918]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'].isin(['HRV','HR-V'])) & 
                            (crash_parties_car_data['Vehicle1Make'] != 'HONDA'), 'Vehicle1Make'] = 'HONDA'

In [1919]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'] == 'BRZ') & 
                            (crash_parties_car_data['Vehicle1Make'] != 'SUBARU'), 'Vehicle1Make'] = 'SUBARU'

In [1920]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'].isin(['EQUINOX','COLORADO'])) & 
                            (crash_parties_car_data['Vehicle1Make'] != 'CHEVROLET'), 'Vehicle1Make'] = 'CHEVROLET'

In [1921]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'].isin(['Q7','Q3'])) & 
                            (crash_parties_car_data['Vehicle1Make'] != 'AUDI'), 'Vehicle1Make'] = 'AUDI'

In [1922]:
crash_parties_car_data.drop(crash_parties_car_data[(crash_parties_car_data['Vehicle1Model'] == 'ES')].index,inplace= True)

In [1923]:
crash_parties_car_data.drop(crash_parties_car_data[crash_parties_car_data['Vehicle1Model'] =='TOYOTA'].index, inplace = True)

In [1924]:
crash_parties_car_data.drop(crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Model'].isna())].index, inplace = True)

In [1925]:
len(crash_parties_car_data)

536296

In [1926]:
crash_parties_car_data['Vehicle1Model'].isna().sum()

np.int64(0)

In [1927]:
#Drop the rows where the Vehicle1Model is NaN since we cannot use them for analysis and it will be too time consuming to cross reference the Vehicle1Make and Vehicle1Year to find out what the Vehicle1Model is.
crash_parties_car_data = crash_parties_car_data.dropna(subset=['Vehicle1Model'])

In [1928]:
#Assert the above is true, if not it will throw an error and stop the program from running
assert(crash_parties_car_data['Vehicle1Model'].isna().sum() == 0)

In [1929]:
crash_parties_car_data['Vehicle1Model'].value_counts()[0:50]

Vehicle1Model
CAMRY          24281
CIVIC          23822
ACCORD         22425
COROLLA        18703
SILVERADO      12440
TACOMA         11758
PRIUS          11544
RAV4            9720
ALTIMA          9186
CRV             8610
MODEL 3         7610
F-150           6825
SENTRA          6752
MODEL Y         6336
RAM 1500        5651
ELANTRA         5454
EXPLORER        5405
HIGHLANDER      4950
SIENNA          4784
ROGUE           4485
SIERRA          4400
3 SERIES        4095
FUSION          4020
TUNDRA          3976
SONATA          3927
MUSTANG         3854
CHARGER         3743
TAHOE           3706
MALIBU          3528
PILOT           3503
4-RUNNER        3323
JETTA           3273
FORTE           3209
F-250           3159
ODYSSEY         3094
ESCAPE          2965
WRANGLER        2863
FORD            2833
UTILITY VAN     2817
VERSA           2724
OPTIMA          2715
FRONTIER        2616
EQUINOX         2518
FOCUS           2503
OUTBACK         2436
RANGER          2392
RAM 2500        2261
CHEROKEE        2197
YUKON           2068
FORESTER        2060
Name: count, dtype: int64

In [1930]:
crash_parties_car_data['Vehicle1Model'].value_counts()[50:100]

Vehicle1Model
GRAND CHEROKEE    1948
HR-V              1904
SOUL              1893
TRANSIT           1889
CAMARO            1846
RX350             1842
COLORADO          1838
SUBURBAN          1831
SORENTO           1788
CX-5              1743
CRUZE             1723
F-350             1690
MDX               1686
TRAVERSE          1685
CHALLENGER        1669
BUS               1664
DURANGO           1657
EDGE              1649
SANTA FE          1602
MAZDA3            1593
CROSSTREK         1546
AVALON            1545
PATHFINDER        1535
FIT               1532
EXPEDITION        1525
C300              1510
ES350             1483
IS250             1395
SPORTAGE          1386
TL                1364
ES300             1299
IMPALA            1244
YARIS             1242
RAM               1197
X5                1167
MODEL S           1163
300 Series        1134
X3                1113
COMPASS           1110
TIGUAN            1094
IMPREZA           1089
G35               1078
E350              1056
ESCALADE          1047
ACCENT            1014
MOTORCYCLE         996
TUSCON             990
A4                 956
PASSAT             943
RAM 3500           929
Name: count, dtype: int64

In [1931]:
crash_parties_car_data['Vehicle1Model'].value_counts()[100:150]

Vehicle1Model
MODEL X          909
Q5               908
MAXIMA           907
OUTLANDER        904
Q50              877
RANGE ROVER      876
BRONCO           864
NIRO             849
TERRAIN          848
PACIFICA         846
TRAX             844
KICKS            841
MAZDA6           835
RDX              825
TSX              810
CASCADIA         808
TRUCK TRACTOR    777
K5               775
MURANO           770
TC               770
SEQUOIA          762
ACADIA           747
VOLT             745
KONA             716
TITAN            714
TUCSON           705
VENZA            698
TAURUS           697
C350             695
F-550            692
XB               684
G37              660
CTS              634
MAVERICK         628
JOURNEY          625
GLC 300          617
FIESTA           614
MATRIX           610
BLAZER           596
BOLT             593
MC               590
RIO              586
GOLF             586
SEMI-TRUCK       581
WRX              576
ATLAS            572
CANYON           568
TRAIL BLAZER     562
DAKOTA           561
COOPER           550
Name: count, dtype: int64

In [1932]:
crash_parties_car_data['Vehicle1Model'].value_counts()[150:200]

Vehicle1Model
LEGACY            535
INSIGHT           526
200               524
CORVETTE          517
CX5               517
S10               515
TELLURIDE         513
IS300             504
IS350             500
FLEX              500
A3                499
F-450             499
INTEGRA           495
SCION             492
TLX               492
Q7                483
IONIQ             483
CX-30             473
PATRIOT           472
X1                470
RIDGELINE         466
M2                458
XC90              449
RENEGADE          447
BICYCLE           438
LANCER            432
XTERRA            431
AVALANCHE         426
LIBERTY           426
SOLARA            424
ENCORE            418
TOWN & COUNTRY    413
528I              412
BOX TRUCK         411
GENESIS           411
ILX               404
530I              400
ARMADA            399
SAVANNA           395
QX60              394
GTI               390
TRAILER           389
RX300             388
BEETLE            373
GRAND CARAVAN     369
K4                369
CROWN VICTORIA    368
CAYENNE           358
ELEMENT           357
ENCLAVE           357
Name: count, dtype: int64

In [1933]:
crash_parties_car_data['Vehicle1Model'].value_counts()[200:250]

Vehicle1Model
GLADIATOR         356
DART              354
NAVIGATOR         353
PROMASTER         352
MIRAGE            348
PALISADE          346
ASCENT            346
C-MAX             346
SEDAN             336
A5                335
GS300             334
E-CLASS           330
Q3                329
NX300             328
PT CRUISER        327
GLE350            323
SONIC             322
IONIQ 5           317
A6                315
MINI COOPER       313
5500              310
500               310
SPARK             306
350Z              303
MACAN             303
ECONOLINE E350    303
GS350             302
430I              295
S60               293
COBALT            292
I4                292
TRAILBLAZER       290
ID4               289
LEAF              287
C-HR              286
E320              283
NV200             280
MKZ               277
CT200H            275
C250              275
RX450             274
CX9               270
R1S               267
VELOSTER          267
TAOS              266
CLARITY           266
ML350             262
SRX               262
SELTOS            261
CYBERTRUCK        261
Name: count, dtype: int64

In [1934]:
crash_parties_car_data['Vehicle1Model'].value_counts()[250:300]

Vehicle1Model
TRACTOR            258
ENVOY              257
SEDONA             256
LACROSSE           253
MIATA              251
EV6                250
PASSPORT           249
QUEST              249
NX350              247
CH-R               245
ACC                244
ES330              243
XC60               237
GL450              235
COROLLA CROSS      234
CLA250             233
DUMP TRUCK         233
PROLOGUE           232
AVENGER            232
VUE                228
CIV                228
RX                 228
CX-9               227
E300               223
DENALI             219
RSX                215
CX-50              213
RX330              210
FJ CRUISER         208
DISCOVERY          208
S550               207
ECONOLINE          206
TOWN CAR           205
SPECTRA            204
F650 SUPER CREW    200
ECLIPSE            199
GR86               194
535I               191
4500               189
CARNIVAL           188
TRANSIT 250        187
GRAND MARQUIS      186
ASTRO VAN          186
BZ4X               183
X6                 183
XTS                182
ES250              182
G6                 182
IS                 182
CELICA             181
Name: count, dtype: int64

In [1935]:
crash_parties_car_data['Vehicle1Model'].value_counts()[300:350]

Vehicle1Model
BRZ                181
ION                180
JUKE               180
GLA250             180
350                179
SCION TC           178
QX50               177
X7                 173
R6                 173
FX35               170
ROAD GLIDE         170
NPR                168
C230               168
ATS                167
STINGER            165
CLA 250            164
300 SERIES         162
E450               162
328                162
FLATBED            161
CALIBER            161
TRANSIT CONNECT    161
PICKUP             160
SCOOTER            158
428I               156
323                155
E-BIKE             153
VOYAGER            152
VENUE              151
IX                 151
OTHER              151
GALANT             150
LAND CRUISER       148
SCION XB           147
MV607              147
VERANO             146
REGAL              145
ECHO               145
M4                 145
ARIYA              144
STREET GLIDE       143
NX                 142
VIBE               142
AVEO               141
WAGONEER           140
X4                 140
MX5                139
540I               138
MIRAI              138
Q8                 136
Name: count, dtype: int64

In [1936]:
crash_parties_car_data['Vehicle1Model'].value_counts()[350:400]

Vehicle1Model
CHASSIS AND CAB    136
Q60                134
MKX                133
SONOMA             133
GX460              133
ECONOLINE 100      133
LS430              132
T680               132
LS460              132
RX3OO              131
LS400              131
COUNTRYMAN         131
TOW TRUCK          130
NX200T             128
150                128
250 SERIES         127
ECOSPORT           127
268                127
CENTURY            126
XT5                126
METRIS             125
CROWN              125
GLA 250            125
EXCURSION          124
F15                123
DEFENDER           123
FRS                123
XPL                122
GLE                122
XC40               120
NRR                119
XA                 119
SEBRING            118
370Z               118
GIULIA             117
ALT                117
740I               117
IA                 116
525I               116
A220               116
RX400              115
CROSSTOUR          114
SLV                114
2                  113
I3                 113
5                  113
530E               112
S-CLASS            112
ROAD KING          112
QX56               112
Name: count, dtype: int64

In [1937]:
crash_parties_car_data['Vehicle1Model'].value_counts()[400:450]

Vehicle1Model
XD                111
250               110
ASTRO             110
GX470             109
CUBE              108
GV80              108
REBEL             107
Q4                107
SPORTSTER         106
GLK350            106
300C              105
MV                105
XT4               105
MAGNUM            104
CAVALIER          104
C240              104
X2                102
550I              102
G70               102
T-100             101
PANAMERA          101
SUPRA             101
535               100
PROTEGE            99
MACH E             99
GLC                98
330E               98
CC                 97
ECONOLINE E150     97
RL                 97
IM                 97
S5                 97
NEON               95
GSXR               94
E250               94
LE SABRE           94
MAZDA 5            94
MONTERO            94
ENVISION           94
PRELUDE            93
S500               93
440I               93
T3                 93
UTILITY            92
325                92
LS                 92
911                92
ML320              92
R3                 91
EV9                91
Name: count, dtype: int64

In [1938]:
crash_parties_car_data['Vehicle1Model'].value_counts()[450:500]

Vehicle1Model
LAREDO              90
228I                90
ROUGE               89
VNL                 89
R1T                 89
ECONOLINE E250      88
TAYCAN              87
RAPTOR              87
M35                 87
XC70                86
TRASH TRUCK         86
GRAND HIGHLANDER    86
CX-90               85
Z4                  85
5 SERIES            85
T880                84
E-450               84
GHIBLI              84
ENVISTA             84
TT                  84
LATITUDE            83
MOUNTAINEER         83
COOPER S            83
R1                  83
QX4                 83
C320                82
567                 82
XCELSIOR            82
TOUAREG             82
A7                  82
GRAND PRIX          81
SANTA CRUZ          80
MACH-E              80
TRIBUTE             80
NITRO               80
ES 350              80
HORNET              80
M2 106              80
COMMANDER           79
TK                  79
CL                  79
CL-CLASS            79
CX7                 79
AIR                 79
XF                  79
S40                 78
GS                  78
GLK 350             77
C43                 77
GLS450              77
Name: count, dtype: int64

After cleaning the vehicle 1 make so that there is less typos and data entry errors in the dataset, it seems to show that there needs to be better standards so less room for errors can be made

Making Category Class Labels for Easier Visualization

In [1939]:
crash_parties_car_data.dropna(subset=['Vehicle1Year'], inplace=True)

In [1940]:
#Assert the above drop with Year was also sucessful since they are interlinked
assert(crash_parties_car_data['Vehicle1Year'].isna().sum() == 0)

In [1941]:
crash_parties_car_data.drop(crash_parties_car_data[crash_parties_car_data['Vehicle1Year'] < 1980].index,inplace = True)

In [1942]:
#Assert the above worked
assert(crash_parties_car_data['Vehicle1Year'].min() >= 1980)

In [1943]:
crash_parties_car_data['CollisionId'] = crash_parties_car_data['CollisionId'].astype(np.int64)

In [1944]:
crash_parties_car_data.head()

,CollisionId,Vehicle1Year,Vehicle1Make,Vehicle1Model,Vehicle1Color,V1IsVehicleTowed
1,4541901,2005.0,FORD,F-150,GRY,True
2,4541901,2002.0,FORD,TAURUS,GLD,True
3,4541900,2001.0,SATURN,ION,GLD,False
4,4541900,2020.0,KIA,OPTIMA,WHI,False
5,4541899,2019.0,TOYOTA,4-RUNNER,BLU,False

Cleaning Up The Color Values

In [1945]:
crash_parties_car_data['Vehicle1Color'] = crash_parties_car_data['Vehicle1Color'].fillna('Unknown')

In [1946]:
crash_parties_car_data['Vehicle1Color'] = crash_parties_car_data['Vehicle1Color'].replace('UNKNOWN', 'Unknown')

In [1947]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Color'] =='Blk') | (crash_parties_car_data['Vehicle1Color'] =='blk') | (crash_parties_car_data['Vehicle1Color'] =='BLACK') | (crash_parties_car_data['Vehicle1Color'] =='black') | (crash_parties_car_data['Vehicle1Color'] =='BLK'), 'Vehicle1Color'] = 'Black'

In [1948]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Color'] =='WHI') | (crash_parties_car_data['Vehicle1Color'] =='whi') | (crash_parties_car_data['Vehicle1Color'] =='WHITE') | (crash_parties_car_data['Vehicle1Color'] =='white') | (crash_parties_car_data['Vehicle1Color'] =='Whi'), 'Vehicle1Color'] = 'White'

In [1949]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Color'] =='GRY') | (crash_parties_car_data['Vehicle1Color'] =='grY') | (crash_parties_car_data['Vehicle1Color'] =='GRAY') | (crash_parties_car_data['Vehicle1Color'] =='gray') | (crash_parties_car_data['Vehicle1Color'] =='GrY'), 'Vehicle1Color'] = 'Gray'

In [1950]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Color'] =='SIL') | (crash_parties_car_data['Vehicle1Color'] =='sil') | (crash_parties_car_data['Vehicle1Color'] =='SILVER') | (crash_parties_car_data['Vehicle1Color'] =='silver') | (crash_parties_car_data['Vehicle1Color'] =='Sil'), 'Vehicle1Color'] = 'Silver'

In [1951]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Color'] =='RED') | (crash_parties_car_data['Vehicle1Color'] =='red') | (crash_parties_car_data['Vehicle1Color'] =='Red') | (crash_parties_car_data['Vehicle1Color'] =='R') , 'Vehicle1Color'] = 'Red'

In [1952]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Color'] =='BLU') | (crash_parties_car_data['Vehicle1Color'] =='blu') | (crash_parties_car_data['Vehicle1Color'] =='BLUE') | (crash_parties_car_data['Vehicle1Color'] =='blue') | (crash_parties_car_data['Vehicle1Color'] =='Blu'), 'Vehicle1Color'] = 'Blue'

In [1953]:
crash_parties_car_data.loc[(crash_parties_car_data['Vehicle1Color'] =='GRN') | (crash_parties_car_data['Vehicle1Color'] =='grn') | (crash_parties_car_data['Vehicle1Color'] =='GREEN') | (crash_parties_car_data['Vehicle1Color'] =='green') | (crash_parties_car_data['Vehicle1Color'] =='Grn'), 'Vehicle1Color'] = 'Green'

In [1954]:
crash_parties_car_data['Vehicle1Color'].value_counts()[0:50]

Vehicle1Color
White        142310
Black         96920
Gray          94906
Silver        64518
Blue          38509
Red           32717
Green          8724
TAN            5168
GLD            4747
Unknown        3826
MAR            3133
YEL            2978
BRO            2353
ONG            1968
DBL            1773
BGE            1579
GOLD           1407
BLK/WHI        1218
LBL             884
BROWN           856
MAROON          837
BEIGE           772
GREY            643
PLE             611
BRZ             610
WHI/            580
WHT             525
DGR             484
BLK/            437
ORANGE          413
WHI/BLU         370
GRY/            370
WHI/BLK         366
CHAMPAGNE       339
WHI             332
YELLOW          303
WHI/ONG         285
TEA             278
SIL/            277
LGR             274
BLK             255
YEL/BLK         241
BURGUNDY        225
WHI/RED         224
BLU/            208
GRY             202
RED/BLK         199
WHI/GRN         197
BLU/WHI         193
PURPLE          178
Name: count, dtype: int64

In [1955]:
crash_parties_car_data.to_csv("crash_parties_car_data.csv", index  = False)

In [1956]:
crash_parties_background_info = crash_parties_data[['CollisionId','PartyType','Special Information','IsAtFault']]

In [1957]:
crash_parties_background_info

        CollisionId PartyType     Special Information IsAtFault
0           4541902    Driver  CELL PHONE USE UNKNOWN      True
1           4541901    Driver   CELL PHONE NOT IN USE       NaN
2           4541901    Driver  CELL PHONE USE UNKNOWN      True
3           4541900    Driver   CELL PHONE NOT IN USE       NaN
4           4541900    Driver   CELL PHONE NOT IN USE       NaN
...             ...       ...                     ...       ...
767047      5105674    Driver   CELL PHONE NOT IN USE      True
767048      5105673    Driver   CELL PHONE NOT IN USE      True
767049      5105672    Driver   CELL PHONE NOT IN USE       NaN
767050      5105672    Driver   CELL PHONE NOT IN USE      True
767051      5105671    Driver   CELL PHONE NOT IN USE       NaN

[765797 rows x 4 columns]

In [1958]:
len((crash_parties_background_info['IsAtFault'] == 'NaN'))

765797

In [1959]:
len(crash_parties_background_info['IsAtFault'] == 'NaN')

765797

In [1960]:
crash_parties_background_info['IsAtFault'].isna().sum()

np.int64(402932)

In [1961]:
len(crash_parties_background_info[crash_parties_background_info['IsAtFault'] == False])

0

In [1962]:
#Assuming that NaN is False since there are no False values in the IsAtFault column, so we can assume that NaN is False since there are no False values in the IsAtFault column. This is a reasonable assumption since if a party was at fault, it would be recorded as True, and if they were not at fault, it would be recorded as False. Therefore, if there is no information about whether a party was at fault or not, we can assume that they were not at fault.
crash_parties_background_info.loc[crash_parties_background_info['IsAtFault'].isna(), 'IsAtFault'] =  False

In [1963]:
#Assert the above is true
assert(crash_parties_background_info['IsAtFault'].isna().sum() == 0)

In [1964]:
crash_parties_background_info

        CollisionId PartyType     Special Information IsAtFault
0           4541902    Driver  CELL PHONE USE UNKNOWN      True
1           4541901    Driver   CELL PHONE NOT IN USE     False
2           4541901    Driver  CELL PHONE USE UNKNOWN      True
3           4541900    Driver   CELL PHONE NOT IN USE     False
4           4541900    Driver   CELL PHONE NOT IN USE     False
...             ...       ...                     ...       ...
767047      5105674    Driver   CELL PHONE NOT IN USE      True
767048      5105673    Driver   CELL PHONE NOT IN USE      True
767049      5105672    Driver   CELL PHONE NOT IN USE     False
767050      5105672    Driver   CELL PHONE NOT IN USE      True
767051      5105671    Driver   CELL PHONE NOT IN USE     False

[765797 rows x 4 columns]

In [1965]:
crash_parties_background_info.to_csv("crash_parties_background_info.csv", index  = False)

Summary:

When it comes to the lack of missing values, it seems that there are no one clear answer to where it is focused on and why it exists. 

When it comes to general missing values, it was used as a placeholder since the entry was missing the value such as boolean column so in that case it was safe to mark it as False. This also applied to IsAtFault, it appears that when it came to marking things as True or False, NaN was used as False instead of actual False. However this also very rampant in columns that are essentially optional to a row due to this in some cases where there are some columns that are majority NaN or missing. These rows containing those missing values were removed after it was taken apart. The ones that were correct were joined back into the original data. 

When it comes to incorrect values, this was especially apparent in columns such as car description (year, model, make, etc.). This made it more challenging since there are so many different ways that this could be handled since considering that there are spelling errors in the string columns, these needed to be handeled by hand. However this is becomes an issue when there are general names as the 3 series from BMW because of that it was easier to join them together then keep seperate them and fracture the dataset. There are also issues such as the Tesla Model Y and 3 since there were entries that interchange them. 

Odd values, this mostly applied to more niche vehicle types such as commerical trucks, box trucks and motorcycles since I do not have a background in this and they are vastly outnumbered by cars, this was not given too much attention in addressing. 

However given the size of this dataset, it was easier to divide the dataset into subsets of themselves so that when it comes to graphing and visualization, it would be easier to pick and choose them by combining them together.